// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/battle/v1/battle.proto

package battlepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateRoomStatus int32

const (
	CreateRoomStatus_CREATE_ROOM_STATUS_UNSPECIFIED     CreateRoomStatus = 0
	CreateRoomStatus_CREATE_ROOM_STATUS_OK              CreateRoomStatus = 1
	CreateRoomStatus_CREATE_ROOM_STATUS_INVALID_REQUEST CreateRoomStatus = 2
	CreateRoomStatus_CREATE_ROOM_STATUS_ALREADY_EXISTS  CreateRoomStatus = 3
	CreateRoomStatus_CREATE_ROOM_STATUS_INTERNAL_ERROR  CreateRoomStatus = 4
)

// Enum value maps for CreateRoomStatus.
var (
	CreateRoomStatus_name = map[int32]string{
		0: "CREATE_ROOM_STATUS_UNSPECIFIED",
		1: "CREATE_ROOM_STATUS_OK",
		2: "CREATE_ROOM_STATUS_INVALID_REQUEST",
		3: "CREATE_ROOM_STATUS_ALREADY_EXISTS",
		4: "CREATE_ROOM_STATUS_INTERNAL_ERROR",
	}
	CreateRoomStatus_value = map[string]int32{
		"CREATE_ROOM_STATUS_UNSPECIFIED":     0,
		"CREATE_ROOM_STATUS_OK":              1,
		"CREATE_ROOM_STATUS_INVALID_REQUEST": 2,
		"CREATE_ROOM_STATUS_ALREADY_EXISTS":  3,
		"CREATE_ROOM_STATUS_INTERNAL_ERROR":  4,
	}
)

func (x CreateRoomStatus) Enum() *CreateRoomStatus {
	p := new(CreateRoomStatus)
	*p = x
	return p
}

func (x CreateRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreateRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_battle_proto_enumTypes[0].Descriptor()
}

func (CreateRoomStatus) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_battle_proto_enumTypes[0]
}

func (x CreateRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreateRoomStatus.Descriptor instead.
func (CreateRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{0}
}

type JoinRoomStatus int32

const (
	JoinRoomStatus_JOIN_ROOM_STATUS_UNSPECIFIED        JoinRoomStatus = 0
	JoinRoomStatus_JOIN_ROOM_STATUS_OK                 JoinRoomStatus = 1
	JoinRoomStatus_JOIN_ROOM_STATUS_INVALID_REQUEST    JoinRoomStatus = 2
	JoinRoomStatus_JOIN_ROOM_STATUS_ROOM_NOT_FOUND     JoinRoomStatus = 3
	JoinRoomStatus_JOIN_ROOM_STATUS_INVALID_TOKEN      JoinRoomStatus = 4
	JoinRoomStatus_JOIN_ROOM_STATUS_PLAYER_NOT_ALLOWED JoinRoomStatus = 5
	JoinRoomStatus_JOIN_ROOM_STATUS_ALREADY_JOINED     JoinRoomStatus = 6
	JoinRoomStatus_JOIN_ROOM_STATUS_INTERNAL_ERROR     JoinRoomStatus = 7
)

// Enum value maps for JoinRoomStatus.
var (
	JoinRoomStatus_name = map[int32]string{
		0: "JOIN_ROOM_STATUS_UNSPECIFIED",
		1: "JOIN_ROOM_STATUS_OK",
		2: "JOIN_ROOM_STATUS_INVALID_REQUEST",
		3: "JOIN_ROOM_STATUS_ROOM_NOT_FOUND",
		4: "JOIN_ROOM_STATUS_INVALID_TOKEN",
		5: "JOIN_ROOM_STATUS_PLAYER_NOT_ALLOWED",
		6: "JOIN_ROOM_STATUS_ALREADY_JOINED",
		7: "JOIN_ROOM_STATUS_INTERNAL_ERROR",
	}
	JoinRoomStatus_value = map[string]int32{
		"JOIN_ROOM_STATUS_UNSPECIFIED":        0,
		"JOIN_ROOM_STATUS_OK":                 1,
		"JOIN_ROOM_STATUS_INVALID_REQUEST":    2,
		"JOIN_ROOM_STATUS_ROOM_NOT_FOUND":     3,
		"JOIN_ROOM_STATUS_INVALID_TOKEN":      4,
		"JOIN_ROOM_STATUS_PLAYER_NOT_ALLOWED": 5,
		"JOIN_ROOM_STATUS_ALREADY_JOINED":     6,
		"JOIN_ROOM_STATUS_INTERNAL_ERROR":     7,
	}
)

func (x JoinRoomStatus) Enum() *JoinRoomStatus {
	p := new(JoinRoomStatus)
	*p = x
	return p
}

func (x JoinRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JoinRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_battle_proto_enumTypes[1].Descriptor()
}

func (JoinRoomStatus) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_battle_proto_enumTypes[1]
}

func (x JoinRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JoinRoomStatus.Descriptor instead.
func (JoinRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{1}
}

type EndRoomStatus int32

const (
	EndRoomStatus_END_ROOM_STATUS_UNSPECIFIED     EndRoomStatus = 0
	EndRoomStatus_END_ROOM_STATUS_OK              EndRoomStatus = 1
	EndRoomStatus_END_ROOM_STATUS_INVALID_REQUEST EndRoomStatus = 2
	EndRoomStatus_END_ROOM_STATUS_ROOM_NOT_FOUND  EndRoomStatus = 3
	EndRoomStatus_END_ROOM_STATUS_INTERNAL_ERROR  EndRoomStatus = 4
)

// Enum value maps for EndRoomStatus.
var (
	EndRoomStatus_name = map[int32]string{
		0: "END_ROOM_STATUS_UNSPECIFIED",
		1: "END_ROOM_STATUS_OK",
		2: "END_ROOM_STATUS_INVALID_REQUEST",
		3: "END_ROOM_STATUS_ROOM_NOT_FOUND",
		4: "END_ROOM_STATUS_INTERNAL_ERROR",
	}
	EndRoomStatus_value = map[string]int32{
		"END_ROOM_STATUS_UNSPECIFIED":     0,
		"END_ROOM_STATUS_OK":              1,
		"END_ROOM_STATUS_INVALID_REQUEST": 2,
		"END_ROOM_STATUS_ROOM_NOT_FOUND":  3,
		"END_ROOM_STATUS_INTERNAL_ERROR":  4,
	}
)

func (x EndRoomStatus) Enum() *EndRoomStatus {
	p := new(EndRoomStatus)
	*p = x
	return p
}

func (x EndRoomStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EndRoomStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_battle_proto_enumTypes[2].Descriptor()
}

func (EndRoomStatus) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_battle_proto_enumTypes[2]
}

func (x EndRoomStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EndRoomStatus.Descriptor instead.
func (EndRoomStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{2}
}

type CreateRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,3,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomRequest) Reset() {
	*x = CreateRoomRequest{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomRequest) ProtoMessage() {}

func (x *CreateRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomRequest.ProtoReflect.Descriptor instead.
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{0}
}

func (x *CreateRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *CreateRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateRoomRequest) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type CreateRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        CreateRoomStatus       `protobuf:"varint,1,opt,name=status,proto3,enum=battle.v1.CreateRoomStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRoomResponse) Reset() {
	*x = CreateRoomResponse{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRoomResponse) ProtoMessage() {}

func (x *CreateRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRoomResponse.ProtoReflect.Descriptor instead.
func (*CreateRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRoomResponse) GetStatus() CreateRoomStatus {
	if x != nil {
		return x.Status
	}
	return CreateRoomStatus_CREATE_ROOM_STATUS_UNSPECIFIED
}

func (x *CreateRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type JoinRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomRequest) Reset() {
	*x = JoinRoomRequest{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomRequest) ProtoMessage() {}

func (x *JoinRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomRequest.ProtoReflect.Descriptor instead.
func (*JoinRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{2}
}

func (x *JoinRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *JoinRoomRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *JoinRoomRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type JoinRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        JoinRoomStatus         `protobuf:"varint,1,opt,name=status,proto3,enum=battle.v1.JoinRoomStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinRoomResponse) Reset() {
	*x = JoinRoomResponse{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinRoomResponse) ProtoMessage() {}

func (x *JoinRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinRoomResponse.ProtoReflect.Descriptor instead.
func (*JoinRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{3}
}

func (x *JoinRoomResponse) GetStatus() JoinRoomStatus {
	if x != nil {
		return x.Status
	}
	return JoinRoomStatus_JOIN_ROOM_STATUS_UNSPECIFIED
}

func (x *JoinRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EndRoomRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoomRequest) Reset() {
	*x = EndRoomRequest{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoomRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoomRequest) ProtoMessage() {}

func (x *EndRoomRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoomRequest.ProtoReflect.Descriptor instead.
func (*EndRoomRequest) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{4}
}

func (x *EndRoomRequest) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *EndRoomRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EndRoomResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        EndRoomStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=battle.v1.EndRoomStatus" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndRoomResponse) Reset() {
	*x = EndRoomResponse{}
	mi := &file_proto_battle_v1_battle_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndRoomResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndRoomResponse) ProtoMessage() {}

func (x *EndRoomResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_battle_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndRoomResponse.ProtoReflect.Descriptor instead.
func (*EndRoomResponse) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_battle_proto_rawDescGZIP(), []int{5}
}

func (x *EndRoomResponse) GetStatus() EndRoomStatus {
	if x != nil {
		return x.Status
	}
	return EndRoomStatus_END_ROOM_STATUS_UNSPECIFIED
}

func (x *EndRoomResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_battle_v1_battle_proto protoreflect.FileDescriptor

const file_proto_battle_v1_battle_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/battle/v1/battle.proto\x12\tbattle.v1\"e\n" +
	"\x11CreateRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x03 \x03(\x03R\tplayerIds\"c\n" +
	"\x12CreateRoomResponse\x123\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1b.battle.v1.CreateRoomStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"a\n" +
	"\x0fJoinRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\"_\n" +
	"\x10JoinRoomResponse\x121\n" +
	"\x06status\x18\x01 \x01(\x0e2\x19.battle.v1.JoinRoomStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"E\n" +
	"\x0eEndRoomRequest\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"]\n" +
	"\x0fEndRoomResponse\x120\n" +
	"\x06status\x18\x01 \x01(\x0e2\x18.battle.v1.EndRoomStatusR\x06status\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\xc7\x01\n" +
	"\x10CreateRoomStatus\x12\"\n" +
	"\x1eCREATE_ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15CREATE_ROOM_STATUS_OK\x10\x01\x12&\n" +
	"\"CREATE_ROOM_STATUS_INVALID_REQUEST\x10\x02\x12%\n" +
	"!CREATE_ROOM_STATUS_ALREADY_EXISTS\x10\x03\x12%\n" +
	"!CREATE_ROOM_STATUS_INTERNAL_ERROR\x10\x04*\xad\x02\n" +
	"\x0eJoinRoomStatus\x12 \n" +
	"\x1cJOIN_ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13JOIN_ROOM_STATUS_OK\x10\x01\x12$\n" +
	" JOIN_ROOM_STATUS_INVALID_REQUEST\x10\x02\x12#\n" +
	"\x1fJOIN_ROOM_STATUS_ROOM_NOT_FOUND\x10\x03\x12\"\n" +
	"\x1eJOIN_ROOM_STATUS_INVALID_TOKEN\x10\x04\x12'\n" +
	"#JOIN_ROOM_STATUS_PLAYER_NOT_ALLOWED\x10\x05\x12#\n" +
	"\x1fJOIN_ROOM_STATUS_ALREADY_JOINED\x10\x06\x12#\n" +
	"\x1fJOIN_ROOM_STATUS_INTERNAL_ERROR\x10\a*\xb5\x01\n" +
	"\rEndRoomStatus\x12\x1f\n" +
	"\x1bEND_ROOM_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12END_ROOM_STATUS_OK\x10\x01\x12#\n" +
	"\x1fEND_ROOM_STATUS_INVALID_REQUEST\x10\x02\x12\"\n" +
	"\x1eEND_ROOM_STATUS_ROOM_NOT_FOUND\x10\x03\x12\"\n" +
	"\x1eEND_ROOM_STATUS_INTERNAL_ERROR\x10\x042\xe8\x01\n" +
	"\x14BattleControlService\x12I\n" +
	"\n" +
	"CreateRoom\x12\x1c.battle.v1.CreateRoomRequest\x1a\x1d.battle.v1.CreateRoomResponse\x12C\n" +
	"\bJoinRoom\x12\x1a.battle.v1.JoinRoomRequest\x1a\x1b.battle.v1.JoinRoomResponse\x12@\n" +
	"\aEndRoom\x12\x19.battle.v1.EndRoomRequest\x1a\x1a.battle.v1.EndRoomResponseB,Z*server/internal/contract/battlepb;battlepbb\x06proto3"

var (
	file_proto_battle_v1_battle_proto_rawDescOnce sync.Once
	file_proto_battle_v1_battle_proto_rawDescData []byte
)

func file_proto_battle_v1_battle_proto_rawDescGZIP() []byte {
	file_proto_battle_v1_battle_proto_rawDescOnce.Do(func() {
		file_proto_battle_v1_battle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_battle_v1_battle_proto_rawDesc), len(file_proto_battle_v1_battle_proto_rawDesc)))
	})
	return file_proto_battle_v1_battle_proto_rawDescData
}

var file_proto_battle_v1_battle_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_battle_v1_battle_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_battle_v1_battle_proto_goTypes = []any{
	(CreateRoomStatus)(0),      // 0: battle.v1.CreateRoomStatus
	(JoinRoomStatus)(0),        // 1: battle.v1.JoinRoomStatus
	(EndRoomStatus)(0),         // 2: battle.v1.EndRoomStatus
	(*CreateRoomRequest)(nil),  // 3: battle.v1.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 4: battle.v1.CreateRoomResponse
	(*JoinRoomRequest)(nil),    // 5: battle.v1.JoinRoomRequest
	(*JoinRoomResponse)(nil),   // 6: battle.v1.JoinRoomResponse
	(*EndRoomRequest)(nil),     // 7: battle.v1.EndRoomRequest
	(*EndRoomResponse)(nil),    // 8: battle.v1.EndRoomResponse
}
var file_proto_battle_v1_battle_proto_depIdxs = []int32{
	0, // 0: battle.v1.CreateRoomResponse.status:type_name -> battle.v1.CreateRoomStatus
	1, // 1: battle.v1.JoinRoomResponse.status:type_name -> battle.v1.JoinRoomStatus
	2, // 2: battle.v1.EndRoomResponse.status:type_name -> battle.v1.EndRoomStatus
	3, // 3: battle.v1.BattleControlService.CreateRoom:input_type -> battle.v1.CreateRoomRequest
	5, // 4: battle.v1.BattleControlService.JoinRoom:input_type -> battle.v1.JoinRoomRequest
	7, // 5: battle.v1.BattleControlService.EndRoom:input_type -> battle.v1.EndRoomRequest
	4, // 6: battle.v1.BattleControlService.CreateRoom:output_type -> battle.v1.CreateRoomResponse
	6, // 7: battle.v1.BattleControlService.JoinRoom:output_type -> battle.v1.JoinRoomResponse
	8, // 8: battle.v1.BattleControlService.EndRoom:output_type -> battle.v1.EndRoomResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_battle_v1_battle_proto_init() }
func file_proto_battle_v1_battle_proto_init() {
	if File_proto_battle_v1_battle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_battle_v1_battle_proto_rawDesc), len(file_proto_battle_v1_battle_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_battle_v1_battle_proto_goTypes,
		DependencyIndexes: file_proto_battle_v1_battle_proto_depIdxs,
		EnumInfos:         file_proto_battle_v1_battle_proto_enumTypes,
		MessageInfos:      file_proto_battle_v1_battle_proto_msgTypes,
	}.Build()
	File_proto_battle_v1_battle_proto = out.File
	file_proto_battle_v1_battle_proto_goTypes = nil
	file_proto_battle_v1_battle_proto_depIdxs = nil
}
