// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/battle/v1/session.proto

package battlepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntityKind int32

const (
	EntityKind_ENTITY_KIND_UNSPECIFIED EntityKind = 0
	EntityKind_ENTITY_KIND_PLAYER      EntityKind = 1
	EntityKind_ENTITY_KIND_MONSTER     EntityKind = 2
	EntityKind_ENTITY_KIND_PROJECTILE  EntityKind = 3
)

// Enum value maps for EntityKind.
var (
	EntityKind_name = map[int32]string{
		0: "ENTITY_KIND_UNSPECIFIED",
		1: "ENTITY_KIND_PLAYER",
		2: "ENTITY_KIND_MONSTER",
		3: "ENTITY_KIND_PROJECTILE",
	}
	EntityKind_value = map[string]int32{
		"ENTITY_KIND_UNSPECIFIED": 0,
		"ENTITY_KIND_PLAYER":      1,
		"ENTITY_KIND_MONSTER":     2,
		"ENTITY_KIND_PROJECTILE":  3,
	}
)

func (x EntityKind) Enum() *EntityKind {
	p := new(EntityKind)
	*p = x
	return p
}

func (x EntityKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntityKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_session_proto_enumTypes[0].Descriptor()
}

func (EntityKind) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_session_proto_enumTypes[0]
}

func (x EntityKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntityKind.Descriptor instead.
func (EntityKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{0}
}

type BattlePhase int32

const (
	BattlePhase_BATTLE_PHASE_UNSPECIFIED      BattlePhase = 0
	BattlePhase_BATTLE_PHASE_FIGHTING         BattlePhase = 1
	BattlePhase_BATTLE_PHASE_REWARD_SELECTION BattlePhase = 2
)

// Enum value maps for BattlePhase.
var (
	BattlePhase_name = map[int32]string{
		0: "BATTLE_PHASE_UNSPECIFIED",
		1: "BATTLE_PHASE_FIGHTING",
		2: "BATTLE_PHASE_REWARD_SELECTION",
	}
	BattlePhase_value = map[string]int32{
		"BATTLE_PHASE_UNSPECIFIED":      0,
		"BATTLE_PHASE_FIGHTING":         1,
		"BATTLE_PHASE_REWARD_SELECTION": 2,
	}
)

func (x BattlePhase) Enum() *BattlePhase {
	p := new(BattlePhase)
	*p = x
	return p
}

func (x BattlePhase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BattlePhase) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_session_proto_enumTypes[1].Descriptor()
}

func (BattlePhase) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_session_proto_enumTypes[1]
}

func (x BattlePhase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BattlePhase.Descriptor instead.
func (BattlePhase) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{1}
}

type BlessingId int32

const (
	BlessingId_BLESSING_ID_UNSPECIFIED     BlessingId = 0
	BlessingId_BLESSING_ID_BURN_ON_HIT     BlessingId = 1
	BlessingId_BLESSING_ID_LIFE_STEAL      BlessingId = 2
	BlessingId_BLESSING_ID_FREEZE_ON_HIT   BlessingId = 3
	BlessingId_BLESSING_ID_CRITICAL_STRIKE BlessingId = 4
	BlessingId_BLESSING_ID_CHAIN_LIGHTNING BlessingId = 5
)

// Enum value maps for BlessingId.
var (
	BlessingId_name = map[int32]string{
		0: "BLESSING_ID_UNSPECIFIED",
		1: "BLESSING_ID_BURN_ON_HIT",
		2: "BLESSING_ID_LIFE_STEAL",
		3: "BLESSING_ID_FREEZE_ON_HIT",
		4: "BLESSING_ID_CRITICAL_STRIKE",
		5: "BLESSING_ID_CHAIN_LIGHTNING",
	}
	BlessingId_value = map[string]int32{
		"BLESSING_ID_UNSPECIFIED":     0,
		"BLESSING_ID_BURN_ON_HIT":     1,
		"BLESSING_ID_LIFE_STEAL":      2,
		"BLESSING_ID_FREEZE_ON_HIT":   3,
		"BLESSING_ID_CRITICAL_STRIKE": 4,
		"BLESSING_ID_CHAIN_LIGHTNING": 5,
	}
)

func (x BlessingId) Enum() *BlessingId {
	p := new(BlessingId)
	*p = x
	return p
}

func (x BlessingId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BlessingId) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_session_proto_enumTypes[2].Descriptor()
}

func (BlessingId) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_session_proto_enumTypes[2]
}

func (x BlessingId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BlessingId.Descriptor instead.
func (BlessingId) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{2}
}

type AttackKind int32

const (
	AttackKind_ATTACK_KIND_UNSPECIFIED AttackKind = 0
	AttackKind_ATTACK_KIND_MELEE       AttackKind = 1
	AttackKind_ATTACK_KIND_PROJECTILE  AttackKind = 2
)

// Enum value maps for AttackKind.
var (
	AttackKind_name = map[int32]string{
		0: "ATTACK_KIND_UNSPECIFIED",
		1: "ATTACK_KIND_MELEE",
		2: "ATTACK_KIND_PROJECTILE",
	}
	AttackKind_value = map[string]int32{
		"ATTACK_KIND_UNSPECIFIED": 0,
		"ATTACK_KIND_MELEE":       1,
		"ATTACK_KIND_PROJECTILE":  2,
	}
)

func (x AttackKind) Enum() *AttackKind {
	p := new(AttackKind)
	*p = x
	return p
}

func (x AttackKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AttackKind) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_battle_v1_session_proto_enumTypes[3].Descriptor()
}

func (AttackKind) Type() protoreflect.EnumType {
	return &file_proto_battle_v1_session_proto_enumTypes[3]
}

func (x AttackKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AttackKind.Descriptor instead.
func (AttackKind) EnumDescriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{3}
}

type ClientHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHello) Reset() {
	*x = ClientHello{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHello) ProtoMessage() {}

func (x *ClientHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHello.ProtoReflect.Descriptor instead.
func (*ClientHello) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *ClientHello) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ClientHello) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientHello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ServerHello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Conv          uint32                 `protobuf:"varint,1,opt,name=conv,proto3" json:"conv,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerHello) Reset() {
	*x = ServerHello{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerHello) ProtoMessage() {}

func (x *ServerHello) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerHello.ProtoReflect.Descriptor instead.
func (*ServerHello) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *ServerHello) GetConv() uint32 {
	if x != nil {
		return x.Conv
	}
	return 0
}

func (x *ServerHello) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GameStart struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStart) Reset() {
	*x = GameStart{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStart) ProtoMessage() {}

func (x *GameStart) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStart.ProtoReflect.Descriptor instead.
func (*GameStart) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *GameStart) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GameStart) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClientPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientPacket_Hello
	//	*ClientPacket_Input
	//	*ClientPacket_ChooseBlessing
	//	*ClientPacket_Heartbeat
	Payload       isClientPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientPacket) Reset() {
	*x = ClientPacket{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientPacket) ProtoMessage() {}

func (x *ClientPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientPacket.ProtoReflect.Descriptor instead.
func (*ClientPacket) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *ClientPacket) GetPayload() isClientPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientPacket) GetHello() *ClientHello {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ClientPacket) GetInput() *ClientInput {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_Input); ok {
			return x.Input
		}
	}
	return nil
}

func (x *ClientPacket) GetChooseBlessing() *ChooseBlessing {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_ChooseBlessing); ok {
			return x.ChooseBlessing
		}
	}
	return nil
}

func (x *ClientPacket) GetHeartbeat() *ClientHeartbeat {
	if x != nil {
		if x, ok := x.Payload.(*ClientPacket_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

type isClientPacket_Payload interface {
	isClientPacket_Payload()
}

type ClientPacket_Hello struct {
	Hello *ClientHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ClientPacket_Input struct {
	Input *ClientInput `protobuf:"bytes,2,opt,name=input,proto3,oneof"`
}

type ClientPacket_ChooseBlessing struct {
	ChooseBlessing *ChooseBlessing `protobuf:"bytes,3,opt,name=choose_blessing,json=chooseBlessing,proto3,oneof"`
}

type ClientPacket_Heartbeat struct {
	Heartbeat *ClientHeartbeat `protobuf:"bytes,4,opt,name=heartbeat,proto3,oneof"`
}

func (*ClientPacket_Hello) isClientPacket_Payload() {}

func (*ClientPacket_Input) isClientPacket_Payload() {}

func (*ClientPacket_ChooseBlessing) isClientPacket_Payload() {}

func (*ClientPacket_Heartbeat) isClientPacket_Payload() {}

type ServerPacket struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerPacket_Hello
	//	*ServerPacket_GameStart
	//	*ServerPacket_Error
	//	*ServerPacket_GameOver
	//	*ServerPacket_Snapshot
	Payload       isServerPacket_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPacket) Reset() {
	*x = ServerPacket{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPacket) ProtoMessage() {}

func (x *ServerPacket) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPacket.ProtoReflect.Descriptor instead.
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ServerPacket) GetPayload() isServerPacket_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerPacket) GetHello() *ServerHello {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *ServerPacket) GetGameStart() *GameStart {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_GameStart); ok {
			return x.GameStart
		}
	}
	return nil
}

func (x *ServerPacket) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerPacket) GetGameOver() *GameOver {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_GameOver); ok {
			return x.GameOver
		}
	}
	return nil
}

func (x *ServerPacket) GetSnapshot() *WorldSnapshot {
	if x != nil {
		if x, ok := x.Payload.(*ServerPacket_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

type isServerPacket_Payload interface {
	isServerPacket_Payload()
}

type ServerPacket_Hello struct {
	Hello *ServerHello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type ServerPacket_GameStart struct {
	GameStart *GameStart `protobuf:"bytes,2,opt,name=game_start,json=gameStart,proto3,oneof"`
}

type ServerPacket_Error struct {
	Error *Error `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

type ServerPacket_GameOver struct {
	GameOver *GameOver `protobuf:"bytes,4,opt,name=game_over,json=gameOver,proto3,oneof"`
}

type ServerPacket_Snapshot struct {
	Snapshot *WorldSnapshot `protobuf:"bytes,5,opt,name=snapshot,proto3,oneof"`
}

func (*ServerPacket_Hello) isServerPacket_Payload() {}

func (*ServerPacket_GameStart) isServerPacket_Payload() {}

func (*ServerPacket_Error) isServerPacket_Payload() {}

func (*ServerPacket_GameOver) isServerPacket_Payload() {}

func (*ServerPacket_Snapshot) isServerPacket_Payload() {}

type GameOver struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerIds     []int64                `protobuf:"varint,2,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	PlayerStats   []*PlayerBattleStats   `protobuf:"bytes,4,rep,name=player_stats,json=playerStats,proto3" json:"player_stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameOver) Reset() {
	*x = GameOver{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameOver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameOver) ProtoMessage() {}

func (x *GameOver) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameOver.ProtoReflect.Descriptor instead.
func (*GameOver) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *GameOver) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *GameOver) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

func (x *GameOver) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GameOver) GetPlayerStats() []*PlayerBattleStats {
	if x != nil {
		return x.PlayerStats
	}
	return nil
}

type PlayerBattleStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	TotalKills    int32                  `protobuf:"varint,2,opt,name=total_kills,json=totalKills,proto3" json:"total_kills,omitempty"`
	Kills         []*MonsterKillCount    `protobuf:"bytes,3,rep,name=kills,proto3" json:"kills,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBattleStats) Reset() {
	*x = PlayerBattleStats{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBattleStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBattleStats) ProtoMessage() {}

func (x *PlayerBattleStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBattleStats.ProtoReflect.Descriptor instead.
func (*PlayerBattleStats) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerBattleStats) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBattleStats) GetTotalKills() int32 {
	if x != nil {
		return x.TotalKills
	}
	return 0
}

func (x *PlayerBattleStats) GetKills() []*MonsterKillCount {
	if x != nil {
		return x.Kills
	}
	return nil
}

type MonsterKillCount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MonsterKind   string                 `protobuf:"bytes,1,opt,name=monster_kind,json=monsterKind,proto3" json:"monster_kind,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MonsterKillCount) Reset() {
	*x = MonsterKillCount{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MonsterKillCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MonsterKillCount) ProtoMessage() {}

func (x *MonsterKillCount) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MonsterKillCount.ProtoReflect.Descriptor instead.
func (*MonsterKillCount) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *MonsterKillCount) GetMonsterKind() string {
	if x != nil {
		return x.MonsterKind
	}
	return ""
}

func (x *MonsterKillCount) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type ClientInput struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RoomName        string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerId        int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	X               float32                `protobuf:"fixed32,3,opt,name=x,proto3" json:"x,omitempty"`
	Y               float32                `protobuf:"fixed32,4,opt,name=y,proto3" json:"y,omitempty"`
	AttackRequested bool                   `protobuf:"varint,5,opt,name=attack_requested,json=attackRequested,proto3" json:"attack_requested,omitempty"`
	DashRequested   bool                   `protobuf:"varint,6,opt,name=dash_requested,json=dashRequested,proto3" json:"dash_requested,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ClientInput) Reset() {
	*x = ClientInput{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInput) ProtoMessage() {}

func (x *ClientInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInput.ProtoReflect.Descriptor instead.
func (*ClientInput) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *ClientInput) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ClientInput) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClientInput) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ClientInput) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ClientInput) GetAttackRequested() bool {
	if x != nil {
		return x.AttackRequested
	}
	return false
}

func (x *ClientInput) GetDashRequested() bool {
	if x != nil {
		return x.DashRequested
	}
	return false
}

type EntitySnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entity        uint64                 `protobuf:"varint,1,opt,name=entity,proto3" json:"entity,omitempty"`
	XPosition     float32                `protobuf:"fixed32,2,opt,name=x_position,json=xPosition,proto3" json:"x_position,omitempty"`
	YPosition     float32                `protobuf:"fixed32,3,opt,name=y_position,json=yPosition,proto3" json:"y_position,omitempty"`
	XDirection    float32                `protobuf:"fixed32,4,opt,name=x_direction,json=xDirection,proto3" json:"x_direction,omitempty"`
	YDirection    float32                `protobuf:"fixed32,5,opt,name=y_direction,json=yDirection,proto3" json:"y_direction,omitempty"`
	CurrentHealth int32                  `protobuf:"varint,6,opt,name=current_health,json=currentHealth,proto3" json:"current_health,omitempty"`
	MaxHealth     int32                  `protobuf:"varint,7,opt,name=max_health,json=maxHealth,proto3" json:"max_health,omitempty"`
	Kind          EntityKind             `protobuf:"varint,8,opt,name=kind,proto3,enum=battle.v1.EntityKind" json:"kind,omitempty"`
	PlayerId      int64                  `protobuf:"varint,9,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	MonsterKind   string                 `protobuf:"bytes,10,opt,name=monster_kind,json=monsterKind,proto3" json:"monster_kind,omitempty"`
	Hero          string                 `protobuf:"bytes,11,opt,name=hero,proto3" json:"hero,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EntitySnapshot) Reset() {
	*x = EntitySnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EntitySnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EntitySnapshot) ProtoMessage() {}

func (x *EntitySnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EntitySnapshot.ProtoReflect.Descriptor instead.
func (*EntitySnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *EntitySnapshot) GetEntity() uint64 {
	if x != nil {
		return x.Entity
	}
	return 0
}

func (x *EntitySnapshot) GetXPosition() float32 {
	if x != nil {
		return x.XPosition
	}
	return 0
}

func (x *EntitySnapshot) GetYPosition() float32 {
	if x != nil {
		return x.YPosition
	}
	return 0
}

func (x *EntitySnapshot) GetXDirection() float32 {
	if x != nil {
		return x.XDirection
	}
	return 0
}

func (x *EntitySnapshot) GetYDirection() float32 {
	if x != nil {
		return x.YDirection
	}
	return 0
}

func (x *EntitySnapshot) GetCurrentHealth() int32 {
	if x != nil {
		return x.CurrentHealth
	}
	return 0
}

func (x *EntitySnapshot) GetMaxHealth() int32 {
	if x != nil {
		return x.MaxHealth
	}
	return 0
}

func (x *EntitySnapshot) GetKind() EntityKind {
	if x != nil {
		return x.Kind
	}
	return EntityKind_ENTITY_KIND_UNSPECIFIED
}

func (x *EntitySnapshot) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *EntitySnapshot) GetMonsterKind() string {
	if x != nil {
		return x.MonsterKind
	}
	return ""
}

func (x *EntitySnapshot) GetHero() string {
	if x != nil {
		return x.Hero
	}
	return ""
}

type PlayerProgressSnapshot struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	PlayerId              int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Level                 int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	Experience            int32                  `protobuf:"varint,3,opt,name=experience,proto3" json:"experience,omitempty"`
	ExperienceToNextLevel int32                  `protobuf:"varint,4,opt,name=experience_to_next_level,json=experienceToNextLevel,proto3" json:"experience_to_next_level,omitempty"`
	PendingUpgradeChoices int32                  `protobuf:"varint,5,opt,name=pending_upgrade_choices,json=pendingUpgradeChoices,proto3" json:"pending_upgrade_choices,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *PlayerProgressSnapshot) Reset() {
	*x = PlayerProgressSnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerProgressSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerProgressSnapshot) ProtoMessage() {}

func (x *PlayerProgressSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerProgressSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerProgressSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *PlayerProgressSnapshot) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerProgressSnapshot) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *PlayerProgressSnapshot) GetExperience() int32 {
	if x != nil {
		return x.Experience
	}
	return 0
}

func (x *PlayerProgressSnapshot) GetExperienceToNextLevel() int32 {
	if x != nil {
		return x.ExperienceToNextLevel
	}
	return 0
}

func (x *PlayerProgressSnapshot) GetPendingUpgradeChoices() int32 {
	if x != nil {
		return x.PendingUpgradeChoices
	}
	return 0
}

type BlessingOptionSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OptionId      int32                  `protobuf:"varint,1,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	BlessingId    BlessingId             `protobuf:"varint,2,opt,name=blessing_id,json=blessingId,proto3,enum=battle.v1.BlessingId" json:"blessing_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlessingOptionSnapshot) Reset() {
	*x = BlessingOptionSnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlessingOptionSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlessingOptionSnapshot) ProtoMessage() {}

func (x *BlessingOptionSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlessingOptionSnapshot.ProtoReflect.Descriptor instead.
func (*BlessingOptionSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *BlessingOptionSnapshot) GetOptionId() int32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

func (x *BlessingOptionSnapshot) GetBlessingId() BlessingId {
	if x != nil {
		return x.BlessingId
	}
	return BlessingId_BLESSING_ID_UNSPECIFIED
}

type PlayerBlessingSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlessingId    BlessingId             `protobuf:"varint,1,opt,name=blessing_id,json=blessingId,proto3,enum=battle.v1.BlessingId" json:"blessing_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerBlessingSnapshot) Reset() {
	*x = PlayerBlessingSnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBlessingSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBlessingSnapshot) ProtoMessage() {}

func (x *PlayerBlessingSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBlessingSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerBlessingSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *PlayerBlessingSnapshot) GetBlessingId() BlessingId {
	if x != nil {
		return x.BlessingId
	}
	return BlessingId_BLESSING_ID_UNSPECIFIED
}

func (x *PlayerBlessingSnapshot) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type PlayerBlessingStateSnapshot struct {
	state          protoimpl.MessageState    `protogen:"open.v1"`
	PlayerId       int64                     `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Blessings      []*PlayerBlessingSnapshot `protobuf:"bytes,2,rep,name=blessings,proto3" json:"blessings,omitempty"`
	CurrentOptions []*BlessingOptionSnapshot `protobuf:"bytes,3,rep,name=current_options,json=currentOptions,proto3" json:"current_options,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlayerBlessingStateSnapshot) Reset() {
	*x = PlayerBlessingStateSnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerBlessingStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerBlessingStateSnapshot) ProtoMessage() {}

func (x *PlayerBlessingStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerBlessingStateSnapshot.ProtoReflect.Descriptor instead.
func (*PlayerBlessingStateSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{14}
}

func (x *PlayerBlessingStateSnapshot) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *PlayerBlessingStateSnapshot) GetBlessings() []*PlayerBlessingSnapshot {
	if x != nil {
		return x.Blessings
	}
	return nil
}

func (x *PlayerBlessingStateSnapshot) GetCurrentOptions() []*BlessingOptionSnapshot {
	if x != nil {
		return x.CurrentOptions
	}
	return nil
}

type AttackEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AttackerEntity  uint64                 `protobuf:"varint,1,opt,name=attacker_entity,json=attackerEntity,proto3" json:"attacker_entity,omitempty"`
	ActionId        uint64                 `protobuf:"varint,2,opt,name=action_id,json=actionId,proto3" json:"action_id,omitempty"`
	AttackKind      AttackKind             `protobuf:"varint,3,opt,name=attack_kind,json=attackKind,proto3,enum=battle.v1.AttackKind" json:"attack_kind,omitempty"`
	XDirection      float32                `protobuf:"fixed32,4,opt,name=x_direction,json=xDirection,proto3" json:"x_direction,omitempty"`
	YDirection      float32                `protobuf:"fixed32,5,opt,name=y_direction,json=yDirection,proto3" json:"y_direction,omitempty"`
	StartTick       uint64                 `protobuf:"varint,6,opt,name=start_tick,json=startTick,proto3" json:"start_tick,omitempty"`
	ActiveStartTick uint64                 `protobuf:"varint,7,opt,name=active_start_tick,json=activeStartTick,proto3" json:"active_start_tick,omitempty"`
	ActiveEndTick   uint64                 `protobuf:"varint,8,opt,name=active_end_tick,json=activeEndTick,proto3" json:"active_end_tick,omitempty"`
	RecoveryEndTick uint64                 `protobuf:"varint,9,opt,name=recovery_end_tick,json=recoveryEndTick,proto3" json:"recovery_end_tick,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AttackEvent) Reset() {
	*x = AttackEvent{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttackEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttackEvent) ProtoMessage() {}

func (x *AttackEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttackEvent.ProtoReflect.Descriptor instead.
func (*AttackEvent) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{15}
}

func (x *AttackEvent) GetAttackerEntity() uint64 {
	if x != nil {
		return x.AttackerEntity
	}
	return 0
}

func (x *AttackEvent) GetActionId() uint64 {
	if x != nil {
		return x.ActionId
	}
	return 0
}

func (x *AttackEvent) GetAttackKind() AttackKind {
	if x != nil {
		return x.AttackKind
	}
	return AttackKind_ATTACK_KIND_UNSPECIFIED
}

func (x *AttackEvent) GetXDirection() float32 {
	if x != nil {
		return x.XDirection
	}
	return 0
}

func (x *AttackEvent) GetYDirection() float32 {
	if x != nil {
		return x.YDirection
	}
	return 0
}

func (x *AttackEvent) GetStartTick() uint64 {
	if x != nil {
		return x.StartTick
	}
	return 0
}

func (x *AttackEvent) GetActiveStartTick() uint64 {
	if x != nil {
		return x.ActiveStartTick
	}
	return 0
}

func (x *AttackEvent) GetActiveEndTick() uint64 {
	if x != nil {
		return x.ActiveEndTick
	}
	return 0
}

func (x *AttackEvent) GetRecoveryEndTick() uint64 {
	if x != nil {
		return x.RecoveryEndTick
	}
	return 0
}

type DeathEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VictimEntity  uint64                 `protobuf:"varint,1,opt,name=victim_entity,json=victimEntity,proto3" json:"victim_entity,omitempty"`
	VictimKind    EntityKind             `protobuf:"varint,2,opt,name=victim_kind,json=victimKind,proto3,enum=battle.v1.EntityKind" json:"victim_kind,omitempty"`
	MonsterKind   string                 `protobuf:"bytes,3,opt,name=monster_kind,json=monsterKind,proto3" json:"monster_kind,omitempty"`
	XPosition     float32                `protobuf:"fixed32,4,opt,name=x_position,json=xPosition,proto3" json:"x_position,omitempty"`
	YPosition     float32                `protobuf:"fixed32,5,opt,name=y_position,json=yPosition,proto3" json:"y_position,omitempty"`
	XDirection    float32                `protobuf:"fixed32,6,opt,name=x_direction,json=xDirection,proto3" json:"x_direction,omitempty"`
	YDirection    float32                `protobuf:"fixed32,7,opt,name=y_direction,json=yDirection,proto3" json:"y_direction,omitempty"`
	KillerEntity  uint64                 `protobuf:"varint,8,opt,name=killer_entity,json=killerEntity,proto3" json:"killer_entity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeathEvent) Reset() {
	*x = DeathEvent{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeathEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeathEvent) ProtoMessage() {}

func (x *DeathEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeathEvent.ProtoReflect.Descriptor instead.
func (*DeathEvent) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{16}
}

func (x *DeathEvent) GetVictimEntity() uint64 {
	if x != nil {
		return x.VictimEntity
	}
	return 0
}

func (x *DeathEvent) GetVictimKind() EntityKind {
	if x != nil {
		return x.VictimKind
	}
	return EntityKind_ENTITY_KIND_UNSPECIFIED
}

func (x *DeathEvent) GetMonsterKind() string {
	if x != nil {
		return x.MonsterKind
	}
	return ""
}

func (x *DeathEvent) GetXPosition() float32 {
	if x != nil {
		return x.XPosition
	}
	return 0
}

func (x *DeathEvent) GetYPosition() float32 {
	if x != nil {
		return x.YPosition
	}
	return 0
}

func (x *DeathEvent) GetXDirection() float32 {
	if x != nil {
		return x.XDirection
	}
	return 0
}

func (x *DeathEvent) GetYDirection() float32 {
	if x != nil {
		return x.YDirection
	}
	return 0
}

func (x *DeathEvent) GetKillerEntity() uint64 {
	if x != nil {
		return x.KillerEntity
	}
	return 0
}

type BattleEvent struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	EventId uint64                 `protobuf:"varint,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*BattleEvent_Attack
	//	*BattleEvent_Death
	Payload       isBattleEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleEvent) Reset() {
	*x = BattleEvent{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleEvent) ProtoMessage() {}

func (x *BattleEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleEvent.ProtoReflect.Descriptor instead.
func (*BattleEvent) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{17}
}

func (x *BattleEvent) GetEventId() uint64 {
	if x != nil {
		return x.EventId
	}
	return 0
}

func (x *BattleEvent) GetPayload() isBattleEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *BattleEvent) GetAttack() *AttackEvent {
	if x != nil {
		if x, ok := x.Payload.(*BattleEvent_Attack); ok {
			return x.Attack
		}
	}
	return nil
}

func (x *BattleEvent) GetDeath() *DeathEvent {
	if x != nil {
		if x, ok := x.Payload.(*BattleEvent_Death); ok {
			return x.Death
		}
	}
	return nil
}

type isBattleEvent_Payload interface {
	isBattleEvent_Payload()
}

type BattleEvent_Attack struct {
	Attack *AttackEvent `protobuf:"bytes,2,opt,name=attack,proto3,oneof"`
}

type BattleEvent_Death struct {
	Death *DeathEvent `protobuf:"bytes,3,opt,name=death,proto3,oneof"`
}

func (*BattleEvent_Attack) isBattleEvent_Payload() {}

func (*BattleEvent_Death) isBattleEvent_Payload() {}

type WorldSnapshot struct {
	state                           protoimpl.MessageState         `protogen:"open.v1"`
	RoomName                        string                         `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Entities                        []*EntitySnapshot              `protobuf:"bytes,2,rep,name=entities,proto3" json:"entities,omitempty"`
	CurrentWave                     int32                          `protobuf:"varint,3,opt,name=current_wave,json=currentWave,proto3" json:"current_wave,omitempty"`
	Phase                           BattlePhase                    `protobuf:"varint,4,opt,name=phase,proto3,enum=battle.v1.BattlePhase" json:"phase,omitempty"`
	RewardSelectionRemainingSeconds float32                        `protobuf:"fixed32,5,opt,name=reward_selection_remaining_seconds,json=rewardSelectionRemainingSeconds,proto3" json:"reward_selection_remaining_seconds,omitempty"`
	PlayerProgress                  []*PlayerProgressSnapshot      `protobuf:"bytes,6,rep,name=player_progress,json=playerProgress,proto3" json:"player_progress,omitempty"`
	PlayerBlessings                 []*PlayerBlessingStateSnapshot `protobuf:"bytes,7,rep,name=player_blessings,json=playerBlessings,proto3" json:"player_blessings,omitempty"`
	ServerTick                      uint64                         `protobuf:"varint,8,opt,name=server_tick,json=serverTick,proto3" json:"server_tick,omitempty"`
	Events                          []*BattleEvent                 `protobuf:"bytes,9,rep,name=events,proto3" json:"events,omitempty"`
	TickRate                        uint32                         `protobuf:"varint,10,opt,name=tick_rate,json=tickRate,proto3" json:"tick_rate,omitempty"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *WorldSnapshot) Reset() {
	*x = WorldSnapshot{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorldSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorldSnapshot) ProtoMessage() {}

func (x *WorldSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorldSnapshot.ProtoReflect.Descriptor instead.
func (*WorldSnapshot) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{18}
}

func (x *WorldSnapshot) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *WorldSnapshot) GetEntities() []*EntitySnapshot {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *WorldSnapshot) GetCurrentWave() int32 {
	if x != nil {
		return x.CurrentWave
	}
	return 0
}

func (x *WorldSnapshot) GetPhase() BattlePhase {
	if x != nil {
		return x.Phase
	}
	return BattlePhase_BATTLE_PHASE_UNSPECIFIED
}

func (x *WorldSnapshot) GetRewardSelectionRemainingSeconds() float32 {
	if x != nil {
		return x.RewardSelectionRemainingSeconds
	}
	return 0
}

func (x *WorldSnapshot) GetPlayerProgress() []*PlayerProgressSnapshot {
	if x != nil {
		return x.PlayerProgress
	}
	return nil
}

func (x *WorldSnapshot) GetPlayerBlessings() []*PlayerBlessingStateSnapshot {
	if x != nil {
		return x.PlayerBlessings
	}
	return nil
}

func (x *WorldSnapshot) GetServerTick() uint64 {
	if x != nil {
		return x.ServerTick
	}
	return 0
}

func (x *WorldSnapshot) GetEvents() []*BattleEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *WorldSnapshot) GetTickRate() uint32 {
	if x != nil {
		return x.TickRate
	}
	return 0
}

type ChooseBlessing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	OptionId      int32                  `protobuf:"varint,3,opt,name=option_id,json=optionId,proto3" json:"option_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChooseBlessing) Reset() {
	*x = ChooseBlessing{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChooseBlessing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChooseBlessing) ProtoMessage() {}

func (x *ChooseBlessing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChooseBlessing.ProtoReflect.Descriptor instead.
func (*ChooseBlessing) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{19}
}

func (x *ChooseBlessing) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ChooseBlessing) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ChooseBlessing) GetOptionId() int32 {
	if x != nil {
		return x.OptionId
	}
	return 0
}

type ClientHeartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomName      string                 `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientHeartbeat) Reset() {
	*x = ClientHeartbeat{}
	mi := &file_proto_battle_v1_session_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientHeartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientHeartbeat) ProtoMessage() {}

func (x *ClientHeartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_battle_v1_session_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientHeartbeat.ProtoReflect.Descriptor instead.
func (*ClientHeartbeat) Descriptor() ([]byte, []int) {
	return file_proto_battle_v1_session_proto_rawDescGZIP(), []int{20}
}

func (x *ClientHeartbeat) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *ClientHeartbeat) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_proto_battle_v1_session_proto protoreflect.FileDescriptor

const file_proto_battle_v1_session_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/battle/v1/session.proto\x12\tbattle.v1\"]\n" +
	"\vClientHello\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\";\n" +
	"\vServerHello\x12\x12\n" +
	"\x04conv\x18\x01 \x01(\rR\x04conv\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"G\n" +
	"\tGameStart\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x03R\tplayerIds\"5\n" +
	"\x05Error\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfb\x01\n" +
	"\fClientPacket\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.battle.v1.ClientHelloH\x00R\x05hello\x12.\n" +
	"\x05input\x18\x02 \x01(\v2\x16.battle.v1.ClientInputH\x00R\x05input\x12D\n" +
	"\x0fchoose_blessing\x18\x03 \x01(\v2\x19.battle.v1.ChooseBlessingH\x00R\x0echooseBlessing\x12:\n" +
	"\theartbeat\x18\x04 \x01(\v2\x1a.battle.v1.ClientHeartbeatH\x00R\theartbeatB\t\n" +
	"\apayload\"\x96\x02\n" +
	"\fServerPacket\x12.\n" +
	"\x05hello\x18\x01 \x01(\v2\x16.battle.v1.ServerHelloH\x00R\x05hello\x125\n" +
	"\n" +
	"game_start\x18\x02 \x01(\v2\x14.battle.v1.GameStartH\x00R\tgameStart\x12(\n" +
	"\x05error\x18\x03 \x01(\v2\x10.battle.v1.ErrorH\x00R\x05error\x122\n" +
	"\tgame_over\x18\x04 \x01(\v2\x13.battle.v1.GameOverH\x00R\bgameOver\x126\n" +
	"\bsnapshot\x18\x05 \x01(\v2\x18.battle.v1.WorldSnapshotH\x00R\bsnapshotB\t\n" +
	"\apayload\"\x9f\x01\n" +
	"\bGameOver\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x02 \x03(\x03R\tplayerIds\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12?\n" +
	"\fplayer_stats\x18\x04 \x03(\v2\x1c.battle.v1.PlayerBattleStatsR\vplayerStats\"\x84\x01\n" +
	"\x11PlayerBattleStats\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vtotal_kills\x18\x02 \x01(\x05R\n" +
	"totalKills\x121\n" +
	"\x05kills\x18\x03 \x03(\v2\x1b.battle.v1.MonsterKillCountR\x05kills\"K\n" +
	"\x10MonsterKillCount\x12!\n" +
	"\fmonster_kind\x18\x01 \x01(\tR\vmonsterKind\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xb5\x01\n" +
	"\vClientInput\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\f\n" +
	"\x01x\x18\x03 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x04 \x01(\x02R\x01y\x12)\n" +
	"\x10attack_requested\x18\x05 \x01(\bR\x0fattackRequested\x12%\n" +
	"\x0edash_requested\x18\x06 \x01(\bR\rdashRequested\"\xed\x02\n" +
	"\x0eEntitySnapshot\x12\x16\n" +
	"\x06entity\x18\x01 \x01(\x04R\x06entity\x12\x1d\n" +
	"\n" +
	"x_position\x18\x02 \x01(\x02R\txPosition\x12\x1d\n" +
	"\n" +
	"y_position\x18\x03 \x01(\x02R\tyPosition\x12\x1f\n" +
	"\vx_direction\x18\x04 \x01(\x02R\n" +
	"xDirection\x12\x1f\n" +
	"\vy_direction\x18\x05 \x01(\x02R\n" +
	"yDirection\x12%\n" +
	"\x0ecurrent_health\x18\x06 \x01(\x05R\rcurrentHealth\x12\x1d\n" +
	"\n" +
	"max_health\x18\a \x01(\x05R\tmaxHealth\x12)\n" +
	"\x04kind\x18\b \x01(\x0e2\x15.battle.v1.EntityKindR\x04kind\x12\x1b\n" +
	"\tplayer_id\x18\t \x01(\x03R\bplayerId\x12!\n" +
	"\fmonster_kind\x18\n" +
	" \x01(\tR\vmonsterKind\x12\x12\n" +
	"\x04hero\x18\v \x01(\tR\x04hero\"\xdc\x01\n" +
	"\x16PlayerProgressSnapshot\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\x12\x1e\n" +
	"\n" +
	"experience\x18\x03 \x01(\x05R\n" +
	"experience\x127\n" +
	"\x18experience_to_next_level\x18\x04 \x01(\x05R\x15experienceToNextLevel\x126\n" +
	"\x17pending_upgrade_choices\x18\x05 \x01(\x05R\x15pendingUpgradeChoices\"m\n" +
	"\x16BlessingOptionSnapshot\x12\x1b\n" +
	"\toption_id\x18\x01 \x01(\x05R\boptionId\x126\n" +
	"\vblessing_id\x18\x02 \x01(\x0e2\x15.battle.v1.BlessingIdR\n" +
	"blessingId\"f\n" +
	"\x16PlayerBlessingSnapshot\x126\n" +
	"\vblessing_id\x18\x01 \x01(\x0e2\x15.battle.v1.BlessingIdR\n" +
	"blessingId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"\xc7\x01\n" +
	"\x1bPlayerBlessingStateSnapshot\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12?\n" +
	"\tblessings\x18\x02 \x03(\v2!.battle.v1.PlayerBlessingSnapshotR\tblessings\x12J\n" +
	"\x0fcurrent_options\x18\x03 \x03(\v2!.battle.v1.BlessingOptionSnapshotR\x0ecurrentOptions\"\xec\x02\n" +
	"\vAttackEvent\x12'\n" +
	"\x0fattacker_entity\x18\x01 \x01(\x04R\x0eattackerEntity\x12\x1b\n" +
	"\taction_id\x18\x02 \x01(\x04R\bactionId\x126\n" +
	"\vattack_kind\x18\x03 \x01(\x0e2\x15.battle.v1.AttackKindR\n" +
	"attackKind\x12\x1f\n" +
	"\vx_direction\x18\x04 \x01(\x02R\n" +
	"xDirection\x12\x1f\n" +
	"\vy_direction\x18\x05 \x01(\x02R\n" +
	"yDirection\x12\x1d\n" +
	"\n" +
	"start_tick\x18\x06 \x01(\x04R\tstartTick\x12*\n" +
	"\x11active_start_tick\x18\a \x01(\x04R\x0factiveStartTick\x12&\n" +
	"\x0factive_end_tick\x18\b \x01(\x04R\ractiveEndTick\x12*\n" +
	"\x11recovery_end_tick\x18\t \x01(\x04R\x0frecoveryEndTick\"\xb1\x02\n" +
	"\n" +
	"DeathEvent\x12#\n" +
	"\rvictim_entity\x18\x01 \x01(\x04R\fvictimEntity\x126\n" +
	"\vvictim_kind\x18\x02 \x01(\x0e2\x15.battle.v1.EntityKindR\n" +
	"victimKind\x12!\n" +
	"\fmonster_kind\x18\x03 \x01(\tR\vmonsterKind\x12\x1d\n" +
	"\n" +
	"x_position\x18\x04 \x01(\x02R\txPosition\x12\x1d\n" +
	"\n" +
	"y_position\x18\x05 \x01(\x02R\tyPosition\x12\x1f\n" +
	"\vx_direction\x18\x06 \x01(\x02R\n" +
	"xDirection\x12\x1f\n" +
	"\vy_direction\x18\a \x01(\x02R\n" +
	"yDirection\x12#\n" +
	"\rkiller_entity\x18\b \x01(\x04R\fkillerEntity\"\x94\x01\n" +
	"\vBattleEvent\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\x04R\aeventId\x120\n" +
	"\x06attack\x18\x02 \x01(\v2\x16.battle.v1.AttackEventH\x00R\x06attack\x12-\n" +
	"\x05death\x18\x03 \x01(\v2\x15.battle.v1.DeathEventH\x00R\x05deathB\t\n" +
	"\apayload\"\x8e\x04\n" +
	"\rWorldSnapshot\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x125\n" +
	"\bentities\x18\x02 \x03(\v2\x19.battle.v1.EntitySnapshotR\bentities\x12!\n" +
	"\fcurrent_wave\x18\x03 \x01(\x05R\vcurrentWave\x12,\n" +
	"\x05phase\x18\x04 \x01(\x0e2\x16.battle.v1.BattlePhaseR\x05phase\x12K\n" +
	"\"reward_selection_remaining_seconds\x18\x05 \x01(\x02R\x1frewardSelectionRemainingSeconds\x12J\n" +
	"\x0fplayer_progress\x18\x06 \x03(\v2!.battle.v1.PlayerProgressSnapshotR\x0eplayerProgress\x12Q\n" +
	"\x10player_blessings\x18\a \x03(\v2&.battle.v1.PlayerBlessingStateSnapshotR\x0fplayerBlessings\x12\x1f\n" +
	"\vserver_tick\x18\b \x01(\x04R\n" +
	"serverTick\x12.\n" +
	"\x06events\x18\t \x03(\v2\x16.battle.v1.BattleEventR\x06events\x12\x1b\n" +
	"\ttick_rate\x18\n" +
	" \x01(\rR\btickRate\"g\n" +
	"\x0eChooseBlessing\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x12\x1b\n" +
	"\toption_id\x18\x03 \x01(\x05R\boptionId\"K\n" +
	"\x0fClientHeartbeat\x12\x1b\n" +
	"\troom_name\x18\x01 \x01(\tR\broomName\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId*v\n" +
	"\n" +
	"EntityKind\x12\x1b\n" +
	"\x17ENTITY_KIND_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12ENTITY_KIND_PLAYER\x10\x01\x12\x17\n" +
	"\x13ENTITY_KIND_MONSTER\x10\x02\x12\x1a\n" +
	"\x16ENTITY_KIND_PROJECTILE\x10\x03*i\n" +
	"\vBattlePhase\x12\x1c\n" +
	"\x18BATTLE_PHASE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15BATTLE_PHASE_FIGHTING\x10\x01\x12!\n" +
	"\x1dBATTLE_PHASE_REWARD_SELECTION\x10\x02*\xc3\x01\n" +
	"\n" +
	"BlessingId\x12\x1b\n" +
	"\x17BLESSING_ID_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17BLESSING_ID_BURN_ON_HIT\x10\x01\x12\x1a\n" +
	"\x16BLESSING_ID_LIFE_STEAL\x10\x02\x12\x1d\n" +
	"\x19BLESSING_ID_FREEZE_ON_HIT\x10\x03\x12\x1f\n" +
	"\x1bBLESSING_ID_CRITICAL_STRIKE\x10\x04\x12\x1f\n" +
	"\x1bBLESSING_ID_CHAIN_LIGHTNING\x10\x05*\\\n" +
	"\n" +
	"AttackKind\x12\x1b\n" +
	"\x17ATTACK_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11ATTACK_KIND_MELEE\x10\x01\x12\x1a\n" +
	"\x16ATTACK_KIND_PROJECTILE\x10\x02B,Z*server/internal/contract/battlepb;battlepbb\x06proto3"

var (
	file_proto_battle_v1_session_proto_rawDescOnce sync.Once
	file_proto_battle_v1_session_proto_rawDescData []byte
)

func file_proto_battle_v1_session_proto_rawDescGZIP() []byte {
	file_proto_battle_v1_session_proto_rawDescOnce.Do(func() {
		file_proto_battle_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_battle_v1_session_proto_rawDesc), len(file_proto_battle_v1_session_proto_rawDesc)))
	})
	return file_proto_battle_v1_session_proto_rawDescData
}

var file_proto_battle_v1_session_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_proto_battle_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_proto_battle_v1_session_proto_goTypes = []any{
	(EntityKind)(0),                     // 0: battle.v1.EntityKind
	(BattlePhase)(0),                    // 1: battle.v1.BattlePhase
	(BlessingId)(0),                     // 2: battle.v1.BlessingId
	(AttackKind)(0),                     // 3: battle.v1.AttackKind
	(*ClientHello)(nil),                 // 4: battle.v1.ClientHello
	(*ServerHello)(nil),                 // 5: battle.v1.ServerHello
	(*GameStart)(nil),                   // 6: battle.v1.GameStart
	(*Error)(nil),                       // 7: battle.v1.Error
	(*ClientPacket)(nil),                // 8: battle.v1.ClientPacket
	(*ServerPacket)(nil),                // 9: battle.v1.ServerPacket
	(*GameOver)(nil),                    // 10: battle.v1.GameOver
	(*PlayerBattleStats)(nil),           // 11: battle.v1.PlayerBattleStats
	(*MonsterKillCount)(nil),            // 12: battle.v1.MonsterKillCount
	(*ClientInput)(nil),                 // 13: battle.v1.ClientInput
	(*EntitySnapshot)(nil),              // 14: battle.v1.EntitySnapshot
	(*PlayerProgressSnapshot)(nil),      // 15: battle.v1.PlayerProgressSnapshot
	(*BlessingOptionSnapshot)(nil),      // 16: battle.v1.BlessingOptionSnapshot
	(*PlayerBlessingSnapshot)(nil),      // 17: battle.v1.PlayerBlessingSnapshot
	(*PlayerBlessingStateSnapshot)(nil), // 18: battle.v1.PlayerBlessingStateSnapshot
	(*AttackEvent)(nil),                 // 19: battle.v1.AttackEvent
	(*DeathEvent)(nil),                  // 20: battle.v1.DeathEvent
	(*BattleEvent)(nil),                 // 21: battle.v1.BattleEvent
	(*WorldSnapshot)(nil),               // 22: battle.v1.WorldSnapshot
	(*ChooseBlessing)(nil),              // 23: battle.v1.ChooseBlessing
	(*ClientHeartbeat)(nil),             // 24: battle.v1.ClientHeartbeat
}
var file_proto_battle_v1_session_proto_depIdxs = []int32{
	4,  // 0: battle.v1.ClientPacket.hello:type_name -> battle.v1.ClientHello
	13, // 1: battle.v1.ClientPacket.input:type_name -> battle.v1.ClientInput
	23, // 2: battle.v1.ClientPacket.choose_blessing:type_name -> battle.v1.ChooseBlessing
	24, // 3: battle.v1.ClientPacket.heartbeat:type_name -> battle.v1.ClientHeartbeat
	5,  // 4: battle.v1.ServerPacket.hello:type_name -> battle.v1.ServerHello
	6,  // 5: battle.v1.ServerPacket.game_start:type_name -> battle.v1.GameStart
	7,  // 6: battle.v1.ServerPacket.error:type_name -> battle.v1.Error
	10, // 7: battle.v1.ServerPacket.game_over:type_name -> battle.v1.GameOver
	22, // 8: battle.v1.ServerPacket.snapshot:type_name -> battle.v1.WorldSnapshot
	11, // 9: battle.v1.GameOver.player_stats:type_name -> battle.v1.PlayerBattleStats
	12, // 10: battle.v1.PlayerBattleStats.kills:type_name -> battle.v1.MonsterKillCount
	0,  // 11: battle.v1.EntitySnapshot.kind:type_name -> battle.v1.EntityKind
	2,  // 12: battle.v1.BlessingOptionSnapshot.blessing_id:type_name -> battle.v1.BlessingId
	2,  // 13: battle.v1.PlayerBlessingSnapshot.blessing_id:type_name -> battle.v1.BlessingId
	17, // 14: battle.v1.PlayerBlessingStateSnapshot.blessings:type_name -> battle.v1.PlayerBlessingSnapshot
	16, // 15: battle.v1.PlayerBlessingStateSnapshot.current_options:type_name -> battle.v1.BlessingOptionSnapshot
	3,  // 16: battle.v1.AttackEvent.attack_kind:type_name -> battle.v1.AttackKind
	0,  // 17: battle.v1.DeathEvent.victim_kind:type_name -> battle.v1.EntityKind
	19, // 18: battle.v1.BattleEvent.attack:type_name -> battle.v1.AttackEvent
	20, // 19: battle.v1.BattleEvent.death:type_name -> battle.v1.DeathEvent
	14, // 20: battle.v1.WorldSnapshot.entities:type_name -> battle.v1.EntitySnapshot
	1,  // 21: battle.v1.WorldSnapshot.phase:type_name -> battle.v1.BattlePhase
	15, // 22: battle.v1.WorldSnapshot.player_progress:type_name -> battle.v1.PlayerProgressSnapshot
	18, // 23: battle.v1.WorldSnapshot.player_blessings:type_name -> battle.v1.PlayerBlessingStateSnapshot
	21, // 24: battle.v1.WorldSnapshot.events:type_name -> battle.v1.BattleEvent
	25, // [25:25] is the sub-list for method output_type
	25, // [25:25] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_proto_battle_v1_session_proto_init() }
func file_proto_battle_v1_session_proto_init() {
	if File_proto_battle_v1_session_proto != nil {
		return
	}
	file_proto_battle_v1_session_proto_msgTypes[4].OneofWrappers = []any{
		(*ClientPacket_Hello)(nil),
		(*ClientPacket_Input)(nil),
		(*ClientPacket_ChooseBlessing)(nil),
		(*ClientPacket_Heartbeat)(nil),
	}
	file_proto_battle_v1_session_proto_msgTypes[5].OneofWrappers = []any{
		(*ServerPacket_Hello)(nil),
		(*ServerPacket_GameStart)(nil),
		(*ServerPacket_Error)(nil),
		(*ServerPacket_GameOver)(nil),
		(*ServerPacket_Snapshot)(nil),
	}
	file_proto_battle_v1_session_proto_msgTypes[17].OneofWrappers = []any{
		(*BattleEvent_Attack)(nil),
		(*BattleEvent_Death)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_battle_v1_session_proto_rawDesc), len(file_proto_battle_v1_session_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_battle_v1_session_proto_goTypes,
		DependencyIndexes: file_proto_battle_v1_session_proto_depIdxs,
		EnumInfos:         file_proto_battle_v1_session_proto_enumTypes,
		MessageInfos:      file_proto_battle_v1_session_proto_msgTypes,
	}.Build()
	File_proto_battle_v1_session_proto = out.File
	file_proto_battle_v1_session_proto_goTypes = nil
	file_proto_battle_v1_session_proto_depIdxs = nil
}
