// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/realtime/v1/realtime.proto

package realtimepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_UNSPECIFIED      ErrorCode = 0
	ErrorCode_UNAUTHENTICATED  ErrorCode = 1
	ErrorCode_INVALID_ARGUMENT ErrorCode = 2
	ErrorCode_NOT_FOUND        ErrorCode = 3
	ErrorCode_CONFLICT         ErrorCode = 4
	ErrorCode_INTERNAL         ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "UNSPECIFIED",
		1: "UNAUTHENTICATED",
		2: "INVALID_ARGUMENT",
		3: "NOT_FOUND",
		4: "CONFLICT",
		5: "INTERNAL",
	}
	ErrorCode_value = map[string]int32{
		"UNSPECIFIED":      0,
		"UNAUTHENTICATED":  1,
		"INVALID_ARGUMENT": 2,
		"NOT_FOUND":        3,
		"CONFLICT":         4,
		"INTERNAL":         5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_realtime_v1_realtime_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_proto_realtime_v1_realtime_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

// ClientEnvelope 表示客户端在 TCP 连接上发送的一次请求。
// 首帧 payload 必须是 AuthenticateRequest。
type ClientEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id 必须非零，用于关联此请求及其服务端响应。
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ClientEnvelope_Authenticate
	//	*ClientEnvelope_Heartbeat
	//	*ClientEnvelope_MatchStart
	//	*ClientEnvelope_MatchCancel
	//	*ClientEnvelope_MatchResume
	Payload       isClientEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEnvelope) Reset() {
	*x = ClientEnvelope{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEnvelope) ProtoMessage() {}

func (x *ClientEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEnvelope.ProtoReflect.Descriptor instead.
func (*ClientEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEnvelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ClientEnvelope) GetPayload() isClientEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ClientEnvelope) GetAuthenticate() *AuthenticateRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Authenticate); ok {
			return x.Authenticate
		}
	}
	return nil
}

func (x *ClientEnvelope) GetHeartbeat() *HeartbeatRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *ClientEnvelope) GetMatchStart() *MatchStartRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_MatchStart); ok {
			return x.MatchStart
		}
	}
	return nil
}

func (x *ClientEnvelope) GetMatchCancel() *MatchCancelRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_MatchCancel); ok {
			return x.MatchCancel
		}
	}
	return nil
}

func (x *ClientEnvelope) GetMatchResume() *MatchResumeRequest {
	if x != nil {
		if x, ok := x.Payload.(*ClientEnvelope_MatchResume); ok {
			return x.MatchResume
		}
	}
	return nil
}

type isClientEnvelope_Payload interface {
	isClientEnvelope_Payload()
}

type ClientEnvelope_Authenticate struct {
	Authenticate *AuthenticateRequest `protobuf:"bytes,10,opt,name=authenticate,proto3,oneof"`
}

type ClientEnvelope_Heartbeat struct {
	Heartbeat *HeartbeatRequest `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type ClientEnvelope_MatchStart struct {
	MatchStart *MatchStartRequest `protobuf:"bytes,12,opt,name=match_start,json=matchStart,proto3,oneof"`
}

type ClientEnvelope_MatchCancel struct {
	MatchCancel *MatchCancelRequest `protobuf:"bytes,13,opt,name=match_cancel,json=matchCancel,proto3,oneof"`
}

type ClientEnvelope_MatchResume struct {
	MatchResume *MatchResumeRequest `protobuf:"bytes,14,opt,name=match_resume,json=matchResume,proto3,oneof"`
}

func (*ClientEnvelope_Authenticate) isClientEnvelope_Payload() {}

func (*ClientEnvelope_Heartbeat) isClientEnvelope_Payload() {}

func (*ClientEnvelope_MatchStart) isClientEnvelope_Payload() {}

func (*ClientEnvelope_MatchCancel) isClientEnvelope_Payload() {}

func (*ClientEnvelope_MatchResume) isClientEnvelope_Payload() {}

// ServerEnvelope 表示服务端响应或主动推送的事件。
type ServerEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// request_id 对应客户端请求；服务端主动推送使用零。
	RequestId uint64 `protobuf:"varint,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerEnvelope_Authenticated
	//	*ServerEnvelope_HeartbeatAck
	//	*ServerEnvelope_MatchResult
	//	*ServerEnvelope_MatchCanceled
	//	*ServerEnvelope_Error
	//	*ServerEnvelope_ConnectionReplaced
	//	*ServerEnvelope_FriendPresenceChanged
	//	*ServerEnvelope_FriendRemoved
	//	*ServerEnvelope_FriendRequestReceived
	//	*ServerEnvelope_FriendRequestHandled
	Payload       isServerEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEnvelope) Reset() {
	*x = ServerEnvelope{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEnvelope) ProtoMessage() {}

func (x *ServerEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEnvelope.ProtoReflect.Descriptor instead.
func (*ServerEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{1}
}

func (x *ServerEnvelope) GetRequestId() uint64 {
	if x != nil {
		return x.RequestId
	}
	return 0
}

func (x *ServerEnvelope) GetPayload() isServerEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerEnvelope) GetAuthenticated() *Authenticated {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Authenticated); ok {
			return x.Authenticated
		}
	}
	return nil
}

func (x *ServerEnvelope) GetHeartbeatAck() *HeartbeatAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_HeartbeatAck); ok {
			return x.HeartbeatAck
		}
	}
	return nil
}

func (x *ServerEnvelope) GetMatchResult() *MatchResult {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_MatchResult); ok {
			return x.MatchResult
		}
	}
	return nil
}

func (x *ServerEnvelope) GetMatchCanceled() *MatchCanceled {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_MatchCanceled); ok {
			return x.MatchCanceled
		}
	}
	return nil
}

func (x *ServerEnvelope) GetError() *ProtocolError {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *ServerEnvelope) GetConnectionReplaced() *ConnectionReplaced {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_ConnectionReplaced); ok {
			return x.ConnectionReplaced
		}
	}
	return nil
}

func (x *ServerEnvelope) GetFriendPresenceChanged() *FriendPresenceChanged {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_FriendPresenceChanged); ok {
			return x.FriendPresenceChanged
		}
	}
	return nil
}

func (x *ServerEnvelope) GetFriendRemoved() *FriendRemoved {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_FriendRemoved); ok {
			return x.FriendRemoved
		}
	}
	return nil
}

func (x *ServerEnvelope) GetFriendRequestReceived() *FriendRequestReceived {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_FriendRequestReceived); ok {
			return x.FriendRequestReceived
		}
	}
	return nil
}

func (x *ServerEnvelope) GetFriendRequestHandled() *FriendRequestHandled {
	if x != nil {
		if x, ok := x.Payload.(*ServerEnvelope_FriendRequestHandled); ok {
			return x.FriendRequestHandled
		}
	}
	return nil
}

type isServerEnvelope_Payload interface {
	isServerEnvelope_Payload()
}

type ServerEnvelope_Authenticated struct {
	Authenticated *Authenticated `protobuf:"bytes,10,opt,name=authenticated,proto3,oneof"`
}

type ServerEnvelope_HeartbeatAck struct {
	HeartbeatAck *HeartbeatAck `protobuf:"bytes,11,opt,name=heartbeat_ack,json=heartbeatAck,proto3,oneof"`
}

type ServerEnvelope_MatchResult struct {
	MatchResult *MatchResult `protobuf:"bytes,12,opt,name=match_result,json=matchResult,proto3,oneof"`
}

type ServerEnvelope_MatchCanceled struct {
	MatchCanceled *MatchCanceled `protobuf:"bytes,13,opt,name=match_canceled,json=matchCanceled,proto3,oneof"`
}

type ServerEnvelope_Error struct {
	Error *ProtocolError `protobuf:"bytes,14,opt,name=error,proto3,oneof"`
}

type ServerEnvelope_ConnectionReplaced struct {
	ConnectionReplaced *ConnectionReplaced `protobuf:"bytes,15,opt,name=connection_replaced,json=connectionReplaced,proto3,oneof"`
}

type ServerEnvelope_FriendPresenceChanged struct {
	FriendPresenceChanged *FriendPresenceChanged `protobuf:"bytes,16,opt,name=friend_presence_changed,json=friendPresenceChanged,proto3,oneof"`
}

type ServerEnvelope_FriendRemoved struct {
	FriendRemoved *FriendRemoved `protobuf:"bytes,17,opt,name=friend_removed,json=friendRemoved,proto3,oneof"`
}

type ServerEnvelope_FriendRequestReceived struct {
	FriendRequestReceived *FriendRequestReceived `protobuf:"bytes,18,opt,name=friend_request_received,json=friendRequestReceived,proto3,oneof"`
}

type ServerEnvelope_FriendRequestHandled struct {
	FriendRequestHandled *FriendRequestHandled `protobuf:"bytes,19,opt,name=friend_request_handled,json=friendRequestHandled,proto3,oneof"`
}

func (*ServerEnvelope_Authenticated) isServerEnvelope_Payload() {}

func (*ServerEnvelope_HeartbeatAck) isServerEnvelope_Payload() {}

func (*ServerEnvelope_MatchResult) isServerEnvelope_Payload() {}

func (*ServerEnvelope_MatchCanceled) isServerEnvelope_Payload() {}

func (*ServerEnvelope_Error) isServerEnvelope_Payload() {}

func (*ServerEnvelope_ConnectionReplaced) isServerEnvelope_Payload() {}

func (*ServerEnvelope_FriendPresenceChanged) isServerEnvelope_Payload() {}

func (*ServerEnvelope_FriendRemoved) isServerEnvelope_Payload() {}

func (*ServerEnvelope_FriendRequestReceived) isServerEnvelope_Payload() {}

func (*ServerEnvelope_FriendRequestHandled) isServerEnvelope_Payload() {}

type Authenticated struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Authenticated) Reset() {
	*x = Authenticated{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Authenticated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Authenticated) ProtoMessage() {}

func (x *Authenticated) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Authenticated.ProtoReflect.Descriptor instead.
func (*Authenticated) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{2}
}

func (x *Authenticated) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{3}
}

type HeartbeatAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatAck) Reset() {
	*x = HeartbeatAck{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatAck) ProtoMessage() {}

func (x *HeartbeatAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatAck.ProtoReflect.Descriptor instead.
func (*HeartbeatAck) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{4}
}

type MatchCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelRequest) Reset() {
	*x = MatchCancelRequest{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelRequest) ProtoMessage() {}

func (x *MatchCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelRequest.ProtoReflect.Descriptor instead.
func (*MatchCancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{5}
}

type MatchResumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchResumeRequest) Reset() {
	*x = MatchResumeRequest{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResumeRequest) ProtoMessage() {}

func (x *MatchResumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResumeRequest.ProtoReflect.Descriptor instead.
func (*MatchResumeRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{6}
}

type MatchStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Weapon        string                 `protobuf:"bytes,1,opt,name=weapon,proto3" json:"weapon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchStartRequest) Reset() {
	*x = MatchStartRequest{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchStartRequest) ProtoMessage() {}

func (x *MatchStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchStartRequest.ProtoReflect.Descriptor instead.
func (*MatchStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{7}
}

func (x *MatchStartRequest) GetWeapon() string {
	if x != nil {
		return x.Weapon
	}
	return ""
}

type MatchCanceled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCanceled) Reset() {
	*x = MatchCanceled{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCanceled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCanceled) ProtoMessage() {}

func (x *MatchCanceled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCanceled.ProtoReflect.Descriptor instead.
func (*MatchCanceled) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{8}
}

type MatchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomName       string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	BattleNodeName string                 `protobuf:"bytes,4,opt,name=battle_node_name,json=battleNodeName,proto3" json:"battle_node_name,omitempty"`
	BattleUdpAddr  string                 `protobuf:"bytes,5,opt,name=battle_udp_addr,json=battleUdpAddr,proto3" json:"battle_udp_addr,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{9}
}

func (x *MatchResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchResult) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *MatchResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MatchResult) GetBattleNodeName() string {
	if x != nil {
		return x.BattleNodeName
	}
	return ""
}

func (x *MatchResult) GetBattleUdpAddr() string {
	if x != nil {
		return x.BattleUdpAddr
	}
	return ""
}

// AuthenticateRequest 必须是新连接发送的第一个 payload。
type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{10}
}

func (x *AuthenticateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ProtocolError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          ErrorCode              `protobuf:"varint,1,opt,name=code,proto3,enum=realtime.v1.ErrorCode" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProtocolError) Reset() {
	*x = ProtocolError{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolError) ProtoMessage() {}

func (x *ProtocolError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolError.ProtoReflect.Descriptor instead.
func (*ProtocolError) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{11}
}

func (x *ProtocolError) GetCode() ErrorCode {
	if x != nil {
		return x.Code
	}
	return ErrorCode_UNSPECIFIED
}

func (x *ProtocolError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ConnectionReplaced struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectionReplaced) Reset() {
	*x = ConnectionReplaced{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectionReplaced) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionReplaced) ProtoMessage() {}

func (x *ConnectionReplaced) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionReplaced.ProtoReflect.Descriptor instead.
func (*ConnectionReplaced) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{12}
}

type FriendPresenceChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Online        bool                   `protobuf:"varint,2,opt,name=online,proto3" json:"online,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendPresenceChanged) Reset() {
	*x = FriendPresenceChanged{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendPresenceChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendPresenceChanged) ProtoMessage() {}

func (x *FriendPresenceChanged) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendPresenceChanged.ProtoReflect.Descriptor instead.
func (*FriendPresenceChanged) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{13}
}

func (x *FriendPresenceChanged) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *FriendPresenceChanged) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *FriendPresenceChanged) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type FriendRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRemoved) Reset() {
	*x = FriendRemoved{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRemoved) ProtoMessage() {}

func (x *FriendRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRemoved.ProtoReflect.Descriptor instead.
func (*FriendRemoved) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{14}
}

func (x *FriendRemoved) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type FriendRequestReceived struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestReceived) Reset() {
	*x = FriendRequestReceived{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestReceived) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestReceived) ProtoMessage() {}

func (x *FriendRequestReceived) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestReceived.ProtoReflect.Descriptor instead.
func (*FriendRequestReceived) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{15}
}

func (x *FriendRequestReceived) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type FriendRequestHandled struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequestHandled) Reset() {
	*x = FriendRequestHandled{}
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequestHandled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequestHandled) ProtoMessage() {}

func (x *FriendRequestHandled) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_realtime_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequestHandled.ProtoReflect.Descriptor instead.
func (*FriendRequestHandled) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_realtime_proto_rawDescGZIP(), []int{16}
}

func (x *FriendRequestHandled) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_proto_realtime_v1_realtime_proto protoreflect.FileDescriptor

const file_proto_realtime_v1_realtime_proto_rawDesc = "" +
	"\n" +
	" proto/realtime/v1/realtime.proto\x12\vrealtime.v1\"\x90\x03\n" +
	"\x0eClientEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12F\n" +
	"\fauthenticate\x18\n" +
	" \x01(\v2 .realtime.v1.AuthenticateRequestH\x00R\fauthenticate\x12=\n" +
	"\theartbeat\x18\v \x01(\v2\x1d.realtime.v1.HeartbeatRequestH\x00R\theartbeat\x12A\n" +
	"\vmatch_start\x18\f \x01(\v2\x1e.realtime.v1.MatchStartRequestH\x00R\n" +
	"matchStart\x12D\n" +
	"\fmatch_cancel\x18\r \x01(\v2\x1f.realtime.v1.MatchCancelRequestH\x00R\vmatchCancel\x12D\n" +
	"\fmatch_resume\x18\x0e \x01(\v2\x1f.realtime.v1.MatchResumeRequestH\x00R\vmatchResumeB\t\n" +
	"\apayload\"\xa8\x06\n" +
	"\x0eServerEnvelope\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\x04R\trequestId\x12B\n" +
	"\rauthenticated\x18\n" +
	" \x01(\v2\x1a.realtime.v1.AuthenticatedH\x00R\rauthenticated\x12@\n" +
	"\rheartbeat_ack\x18\v \x01(\v2\x19.realtime.v1.HeartbeatAckH\x00R\fheartbeatAck\x12=\n" +
	"\fmatch_result\x18\f \x01(\v2\x18.realtime.v1.MatchResultH\x00R\vmatchResult\x12C\n" +
	"\x0ematch_canceled\x18\r \x01(\v2\x1a.realtime.v1.MatchCanceledH\x00R\rmatchCanceled\x122\n" +
	"\x05error\x18\x0e \x01(\v2\x1a.realtime.v1.ProtocolErrorH\x00R\x05error\x12R\n" +
	"\x13connection_replaced\x18\x0f \x01(\v2\x1f.realtime.v1.ConnectionReplacedH\x00R\x12connectionReplaced\x12\\\n" +
	"\x17friend_presence_changed\x18\x10 \x01(\v2\".realtime.v1.FriendPresenceChangedH\x00R\x15friendPresenceChanged\x12C\n" +
	"\x0efriend_removed\x18\x11 \x01(\v2\x1a.realtime.v1.FriendRemovedH\x00R\rfriendRemoved\x12\\\n" +
	"\x17friend_request_received\x18\x12 \x01(\v2\".realtime.v1.FriendRequestReceivedH\x00R\x15friendRequestReceived\x12Y\n" +
	"\x16friend_request_handled\x18\x13 \x01(\v2!.realtime.v1.FriendRequestHandledH\x00R\x14friendRequestHandledB\t\n" +
	"\apayload\",\n" +
	"\rAuthenticated\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x12\n" +
	"\x10HeartbeatRequest\"\x0e\n" +
	"\fHeartbeatAck\"\x14\n" +
	"\x12MatchCancelRequest\"\x14\n" +
	"\x12MatchResumeRequest\"+\n" +
	"\x11MatchStartRequest\x12\x16\n" +
	"\x06weapon\x18\x01 \x01(\tR\x06weapon\"\x0f\n" +
	"\rMatchCanceled\"\xaa\x01\n" +
	"\vMatchResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x10battle_node_name\x18\x04 \x01(\tR\x0ebattleNodeName\x12&\n" +
	"\x0fbattle_udp_addr\x18\x05 \x01(\tR\rbattleUdpAddr\"+\n" +
	"\x13AuthenticateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"U\n" +
	"\rProtocolError\x12*\n" +
	"\x04code\x18\x01 \x01(\x0e2\x16.realtime.v1.ErrorCodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x14\n" +
	"\x12ConnectionReplaced\"d\n" +
	"\x15FriendPresenceChanged\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x16\n" +
	"\x06online\x18\x02 \x01(\bR\x06online\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\",\n" +
	"\rFriendRemoved\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"4\n" +
	"\x15FriendRequestReceived\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"3\n" +
	"\x14FriendRequestHandled\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId*r\n" +
	"\tErrorCode\x12\x0f\n" +
	"\vUNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fUNAUTHENTICATED\x10\x01\x12\x14\n" +
	"\x10INVALID_ARGUMENT\x10\x02\x12\r\n" +
	"\tNOT_FOUND\x10\x03\x12\f\n" +
	"\bCONFLICT\x10\x04\x12\f\n" +
	"\bINTERNAL\x10\x05B0Z.server/internal/contract/realtimepb;realtimepbb\x06proto3"

var (
	file_proto_realtime_v1_realtime_proto_rawDescOnce sync.Once
	file_proto_realtime_v1_realtime_proto_rawDescData []byte
)

func file_proto_realtime_v1_realtime_proto_rawDescGZIP() []byte {
	file_proto_realtime_v1_realtime_proto_rawDescOnce.Do(func() {
		file_proto_realtime_v1_realtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_realtime_proto_rawDesc), len(file_proto_realtime_v1_realtime_proto_rawDesc)))
	})
	return file_proto_realtime_v1_realtime_proto_rawDescData
}

var file_proto_realtime_v1_realtime_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_realtime_v1_realtime_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_realtime_v1_realtime_proto_goTypes = []any{
	(ErrorCode)(0),                // 0: realtime.v1.ErrorCode
	(*ClientEnvelope)(nil),        // 1: realtime.v1.ClientEnvelope
	(*ServerEnvelope)(nil),        // 2: realtime.v1.ServerEnvelope
	(*Authenticated)(nil),         // 3: realtime.v1.Authenticated
	(*HeartbeatRequest)(nil),      // 4: realtime.v1.HeartbeatRequest
	(*HeartbeatAck)(nil),          // 5: realtime.v1.HeartbeatAck
	(*MatchCancelRequest)(nil),    // 6: realtime.v1.MatchCancelRequest
	(*MatchResumeRequest)(nil),    // 7: realtime.v1.MatchResumeRequest
	(*MatchStartRequest)(nil),     // 8: realtime.v1.MatchStartRequest
	(*MatchCanceled)(nil),         // 9: realtime.v1.MatchCanceled
	(*MatchResult)(nil),           // 10: realtime.v1.MatchResult
	(*AuthenticateRequest)(nil),   // 11: realtime.v1.AuthenticateRequest
	(*ProtocolError)(nil),         // 12: realtime.v1.ProtocolError
	(*ConnectionReplaced)(nil),    // 13: realtime.v1.ConnectionReplaced
	(*FriendPresenceChanged)(nil), // 14: realtime.v1.FriendPresenceChanged
	(*FriendRemoved)(nil),         // 15: realtime.v1.FriendRemoved
	(*FriendRequestReceived)(nil), // 16: realtime.v1.FriendRequestReceived
	(*FriendRequestHandled)(nil),  // 17: realtime.v1.FriendRequestHandled
}
var file_proto_realtime_v1_realtime_proto_depIdxs = []int32{
	11, // 0: realtime.v1.ClientEnvelope.authenticate:type_name -> realtime.v1.AuthenticateRequest
	4,  // 1: realtime.v1.ClientEnvelope.heartbeat:type_name -> realtime.v1.HeartbeatRequest
	8,  // 2: realtime.v1.ClientEnvelope.match_start:type_name -> realtime.v1.MatchStartRequest
	6,  // 3: realtime.v1.ClientEnvelope.match_cancel:type_name -> realtime.v1.MatchCancelRequest
	7,  // 4: realtime.v1.ClientEnvelope.match_resume:type_name -> realtime.v1.MatchResumeRequest
	3,  // 5: realtime.v1.ServerEnvelope.authenticated:type_name -> realtime.v1.Authenticated
	5,  // 6: realtime.v1.ServerEnvelope.heartbeat_ack:type_name -> realtime.v1.HeartbeatAck
	10, // 7: realtime.v1.ServerEnvelope.match_result:type_name -> realtime.v1.MatchResult
	9,  // 8: realtime.v1.ServerEnvelope.match_canceled:type_name -> realtime.v1.MatchCanceled
	12, // 9: realtime.v1.ServerEnvelope.error:type_name -> realtime.v1.ProtocolError
	13, // 10: realtime.v1.ServerEnvelope.connection_replaced:type_name -> realtime.v1.ConnectionReplaced
	14, // 11: realtime.v1.ServerEnvelope.friend_presence_changed:type_name -> realtime.v1.FriendPresenceChanged
	15, // 12: realtime.v1.ServerEnvelope.friend_removed:type_name -> realtime.v1.FriendRemoved
	16, // 13: realtime.v1.ServerEnvelope.friend_request_received:type_name -> realtime.v1.FriendRequestReceived
	17, // 14: realtime.v1.ServerEnvelope.friend_request_handled:type_name -> realtime.v1.FriendRequestHandled
	0,  // 15: realtime.v1.ProtocolError.code:type_name -> realtime.v1.ErrorCode
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_realtime_v1_realtime_proto_init() }
func file_proto_realtime_v1_realtime_proto_init() {
	if File_proto_realtime_v1_realtime_proto != nil {
		return
	}
	file_proto_realtime_v1_realtime_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEnvelope_Authenticate)(nil),
		(*ClientEnvelope_Heartbeat)(nil),
		(*ClientEnvelope_MatchStart)(nil),
		(*ClientEnvelope_MatchCancel)(nil),
		(*ClientEnvelope_MatchResume)(nil),
	}
	file_proto_realtime_v1_realtime_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerEnvelope_Authenticated)(nil),
		(*ServerEnvelope_HeartbeatAck)(nil),
		(*ServerEnvelope_MatchResult)(nil),
		(*ServerEnvelope_MatchCanceled)(nil),
		(*ServerEnvelope_Error)(nil),
		(*ServerEnvelope_ConnectionReplaced)(nil),
		(*ServerEnvelope_FriendPresenceChanged)(nil),
		(*ServerEnvelope_FriendRemoved)(nil),
		(*ServerEnvelope_FriendRequestReceived)(nil),
		(*ServerEnvelope_FriendRequestHandled)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_realtime_proto_rawDesc), len(file_proto_realtime_v1_realtime_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_realtime_v1_realtime_proto_goTypes,
		DependencyIndexes: file_proto_realtime_v1_realtime_proto_depIdxs,
		EnumInfos:         file_proto_realtime_v1_realtime_proto_enumTypes,
		MessageInfos:      file_proto_realtime_v1_realtime_proto_msgTypes,
	}.Build()
	File_proto_realtime_v1_realtime_proto = out.File
	file_proto_realtime_v1_realtime_proto_goTypes = nil
	file_proto_realtime_v1_realtime_proto_depIdxs = nil
}
