// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/rcenter/v1/rcenter.proto

package rcenterpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BattleNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KcpAddr       string                 `protobuf:"bytes,2,opt,name=kcp_addr,json=kcpAddr,proto3" json:"kcp_addr,omitempty"`
	ControlAddr   string                 `protobuf:"bytes,3,opt,name=control_addr,json=controlAddr,proto3" json:"control_addr,omitempty"`
	MaxPlayers    int32                  `protobuf:"varint,4,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	ActivePlayers int32                  `protobuf:"varint,5,opt,name=active_players,json=activePlayers,proto3" json:"active_players,omitempty"`
	LastSeenUnix  int64                  `protobuf:"varint,6,opt,name=last_seen_unix,json=lastSeenUnix,proto3" json:"last_seen_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BattleNode) Reset() {
	*x = BattleNode{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BattleNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BattleNode) ProtoMessage() {}

func (x *BattleNode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BattleNode.ProtoReflect.Descriptor instead.
func (*BattleNode) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{0}
}

func (x *BattleNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BattleNode) GetKcpAddr() string {
	if x != nil {
		return x.KcpAddr
	}
	return ""
}

func (x *BattleNode) GetControlAddr() string {
	if x != nil {
		return x.ControlAddr
	}
	return ""
}

func (x *BattleNode) GetMaxPlayers() int32 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

func (x *BattleNode) GetActivePlayers() int32 {
	if x != nil {
		return x.ActivePlayers
	}
	return 0
}

func (x *BattleNode) GetLastSeenUnix() int64 {
	if x != nil {
		return x.LastSeenUnix
	}
	return 0
}

type MatchResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Status         string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	RoomName       string                 `protobuf:"bytes,2,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	Token          string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`
	BattleNodeName string                 `protobuf:"bytes,4,opt,name=battle_node_name,json=battleNodeName,proto3" json:"battle_node_name,omitempty"`
	BattleKcpAddr  string                 `protobuf:"bytes,5,opt,name=battle_kcp_addr,json=battleKcpAddr,proto3" json:"battle_kcp_addr,omitempty"`
	PlayerIds      []int64                `protobuf:"varint,6,rep,packed,name=player_ids,json=playerIds,proto3" json:"player_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MatchResult) Reset() {
	*x = MatchResult{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchResult) ProtoMessage() {}

func (x *MatchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchResult.ProtoReflect.Descriptor instead.
func (*MatchResult) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{1}
}

func (x *MatchResult) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MatchResult) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *MatchResult) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *MatchResult) GetBattleNodeName() string {
	if x != nil {
		return x.BattleNodeName
	}
	return ""
}

func (x *MatchResult) GetBattleKcpAddr() string {
	if x != nil {
		return x.BattleKcpAddr
	}
	return ""
}

func (x *MatchResult) GetPlayerIds() []int64 {
	if x != nil {
		return x.PlayerIds
	}
	return nil
}

type RegisterBattleNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *BattleNode            `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBattleNodeRequest) Reset() {
	*x = RegisterBattleNodeRequest{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBattleNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBattleNodeRequest) ProtoMessage() {}

func (x *RegisterBattleNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBattleNodeRequest.ProtoReflect.Descriptor instead.
func (*RegisterBattleNodeRequest) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterBattleNodeRequest) GetNode() *BattleNode {
	if x != nil {
		return x.Node
	}
	return nil
}

type RegisterBattleNodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterBattleNodeResponse) Reset() {
	*x = RegisterBattleNodeResponse{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterBattleNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterBattleNodeResponse) ProtoMessage() {}

func (x *RegisterBattleNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterBattleNodeResponse.ProtoReflect.Descriptor instead.
func (*RegisterBattleNodeResponse) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{3}
}

type ListBattleNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBattleNodesRequest) Reset() {
	*x = ListBattleNodesRequest{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBattleNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBattleNodesRequest) ProtoMessage() {}

func (x *ListBattleNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBattleNodesRequest.ProtoReflect.Descriptor instead.
func (*ListBattleNodesRequest) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{4}
}

type ListBattleNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*BattleNode          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBattleNodesResponse) Reset() {
	*x = ListBattleNodesResponse{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBattleNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBattleNodesResponse) ProtoMessage() {}

func (x *ListBattleNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBattleNodesResponse.ProtoReflect.Descriptor instead.
func (*ListBattleNodesResponse) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{5}
}

func (x *ListBattleNodesResponse) GetNodes() []*BattleNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type StartMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchRequest) Reset() {
	*x = StartMatchRequest{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchRequest) ProtoMessage() {}

func (x *StartMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchRequest.ProtoReflect.Descriptor instead.
func (*StartMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{6}
}

func (x *StartMatchRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type StartMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        *MatchResult           `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartMatchResponse) Reset() {
	*x = StartMatchResponse{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartMatchResponse) ProtoMessage() {}

func (x *StartMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartMatchResponse.ProtoReflect.Descriptor instead.
func (*StartMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{7}
}

func (x *StartMatchResponse) GetResult() *MatchResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type CancelMatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchRequest) Reset() {
	*x = CancelMatchRequest{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRequest) ProtoMessage() {}

func (x *CancelMatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{8}
}

func (x *CancelMatchRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type CancelMatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelMatchResponse) Reset() {
	*x = CancelMatchResponse{}
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchResponse) ProtoMessage() {}

func (x *CancelMatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rcenter_v1_rcenter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchResponse.ProtoReflect.Descriptor instead.
func (*CancelMatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_rcenter_v1_rcenter_proto_rawDescGZIP(), []int{9}
}

var File_proto_rcenter_v1_rcenter_proto protoreflect.FileDescriptor

const file_proto_rcenter_v1_rcenter_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/rcenter/v1/rcenter.proto\x12\n" +
	"rcenter.v1\"\xcc\x01\n" +
	"\n" +
	"BattleNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x19\n" +
	"\bkcp_addr\x18\x02 \x01(\tR\akcpAddr\x12!\n" +
	"\fcontrol_addr\x18\x03 \x01(\tR\vcontrolAddr\x12\x1f\n" +
	"\vmax_players\x18\x04 \x01(\x05R\n" +
	"maxPlayers\x12%\n" +
	"\x0eactive_players\x18\x05 \x01(\x05R\ractivePlayers\x12$\n" +
	"\x0elast_seen_unix\x18\x06 \x01(\x03R\flastSeenUnix\"\xc9\x01\n" +
	"\vMatchResult\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x1b\n" +
	"\troom_name\x18\x02 \x01(\tR\broomName\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token\x12(\n" +
	"\x10battle_node_name\x18\x04 \x01(\tR\x0ebattleNodeName\x12&\n" +
	"\x0fbattle_kcp_addr\x18\x05 \x01(\tR\rbattleKcpAddr\x12\x1d\n" +
	"\n" +
	"player_ids\x18\x06 \x03(\x03R\tplayerIds\"G\n" +
	"\x19RegisterBattleNodeRequest\x12*\n" +
	"\x04node\x18\x01 \x01(\v2\x16.rcenter.v1.BattleNodeR\x04node\"\x1c\n" +
	"\x1aRegisterBattleNodeResponse\"\x18\n" +
	"\x16ListBattleNodesRequest\"G\n" +
	"\x17ListBattleNodesResponse\x12,\n" +
	"\x05nodes\x18\x01 \x03(\v2\x16.rcenter.v1.BattleNodeR\x05nodes\"0\n" +
	"\x11StartMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"E\n" +
	"\x12StartMatchResponse\x12/\n" +
	"\x06result\x18\x01 \x01(\v2\x17.rcenter.v1.MatchResultR\x06result\"1\n" +
	"\x12CancelMatchRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"\x15\n" +
	"\x13CancelMatchResponse2\xee\x02\n" +
	"\x0eRCenterService\x12c\n" +
	"\x12RegisterBattleNode\x12%.rcenter.v1.RegisterBattleNodeRequest\x1a&.rcenter.v1.RegisterBattleNodeResponse\x12Z\n" +
	"\x0fListBattleNodes\x12\".rcenter.v1.ListBattleNodesRequest\x1a#.rcenter.v1.ListBattleNodesResponse\x12K\n" +
	"\n" +
	"StartMatch\x12\x1d.rcenter.v1.StartMatchRequest\x1a\x1e.rcenter.v1.StartMatchResponse\x12N\n" +
	"\vCancelMatch\x12\x1e.rcenter.v1.CancelMatchRequest\x1a\x1f.rcenter.v1.CancelMatchResponseB.Z,server/internal/contract/rcenterpb;rcenterpbb\x06proto3"

var (
	file_proto_rcenter_v1_rcenter_proto_rawDescOnce sync.Once
	file_proto_rcenter_v1_rcenter_proto_rawDescData []byte
)

func file_proto_rcenter_v1_rcenter_proto_rawDescGZIP() []byte {
	file_proto_rcenter_v1_rcenter_proto_rawDescOnce.Do(func() {
		file_proto_rcenter_v1_rcenter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rcenter_v1_rcenter_proto_rawDesc), len(file_proto_rcenter_v1_rcenter_proto_rawDesc)))
	})
	return file_proto_rcenter_v1_rcenter_proto_rawDescData
}

var file_proto_rcenter_v1_rcenter_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_rcenter_v1_rcenter_proto_goTypes = []any{
	(*BattleNode)(nil),                 // 0: rcenter.v1.BattleNode
	(*MatchResult)(nil),                // 1: rcenter.v1.MatchResult
	(*RegisterBattleNodeRequest)(nil),  // 2: rcenter.v1.RegisterBattleNodeRequest
	(*RegisterBattleNodeResponse)(nil), // 3: rcenter.v1.RegisterBattleNodeResponse
	(*ListBattleNodesRequest)(nil),     // 4: rcenter.v1.ListBattleNodesRequest
	(*ListBattleNodesResponse)(nil),    // 5: rcenter.v1.ListBattleNodesResponse
	(*StartMatchRequest)(nil),          // 6: rcenter.v1.StartMatchRequest
	(*StartMatchResponse)(nil),         // 7: rcenter.v1.StartMatchResponse
	(*CancelMatchRequest)(nil),         // 8: rcenter.v1.CancelMatchRequest
	(*CancelMatchResponse)(nil),        // 9: rcenter.v1.CancelMatchResponse
}
var file_proto_rcenter_v1_rcenter_proto_depIdxs = []int32{
	0, // 0: rcenter.v1.RegisterBattleNodeRequest.node:type_name -> rcenter.v1.BattleNode
	0, // 1: rcenter.v1.ListBattleNodesResponse.nodes:type_name -> rcenter.v1.BattleNode
	1, // 2: rcenter.v1.StartMatchResponse.result:type_name -> rcenter.v1.MatchResult
	2, // 3: rcenter.v1.RCenterService.RegisterBattleNode:input_type -> rcenter.v1.RegisterBattleNodeRequest
	4, // 4: rcenter.v1.RCenterService.ListBattleNodes:input_type -> rcenter.v1.ListBattleNodesRequest
	6, // 5: rcenter.v1.RCenterService.StartMatch:input_type -> rcenter.v1.StartMatchRequest
	8, // 6: rcenter.v1.RCenterService.CancelMatch:input_type -> rcenter.v1.CancelMatchRequest
	3, // 7: rcenter.v1.RCenterService.RegisterBattleNode:output_type -> rcenter.v1.RegisterBattleNodeResponse
	5, // 8: rcenter.v1.RCenterService.ListBattleNodes:output_type -> rcenter.v1.ListBattleNodesResponse
	7, // 9: rcenter.v1.RCenterService.StartMatch:output_type -> rcenter.v1.StartMatchResponse
	9, // 10: rcenter.v1.RCenterService.CancelMatch:output_type -> rcenter.v1.CancelMatchResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_rcenter_v1_rcenter_proto_init() }
func file_proto_rcenter_v1_rcenter_proto_init() {
	if File_proto_rcenter_v1_rcenter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rcenter_v1_rcenter_proto_rawDesc), len(file_proto_rcenter_v1_rcenter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rcenter_v1_rcenter_proto_goTypes,
		DependencyIndexes: file_proto_rcenter_v1_rcenter_proto_depIdxs,
		MessageInfos:      file_proto_rcenter_v1_rcenter_proto_msgTypes,
	}.Build()
	File_proto_rcenter_v1_rcenter_proto = out.File
	file_proto_rcenter_v1_rcenter_proto_goTypes = nil
	file_proto_rcenter_v1_rcenter_proto_depIdxs = nil
}
