// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.31.1
// source: proto/rcenter/v1/rcenter.proto

package rcenterpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RCenterService_RegisterBattleNode_FullMethodName = "/rcenter.v1.RCenterService/RegisterBattleNode"
	RCenterService_ListBattleNodes_FullMethodName    = "/rcenter.v1.RCenterService/ListBattleNodes"
	RCenterService_StartMatch_FullMethodName         = "/rcenter.v1.RCenterService/StartMatch"
	RCenterService_CancelMatch_FullMethodName        = "/rcenter.v1.RCenterService/CancelMatch"
)

// RCenterServiceClient is the client API for RCenterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RCenterServiceClient interface {
	RegisterBattleNode(ctx context.Context, in *RegisterBattleNodeRequest, opts ...grpc.CallOption) (*RegisterBattleNodeResponse, error)
	ListBattleNodes(ctx context.Context, in *ListBattleNodesRequest, opts ...grpc.CallOption) (*ListBattleNodesResponse, error)
	StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*StartMatchResponse, error)
	CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchResponse, error)
}

type rCenterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRCenterServiceClient(cc grpc.ClientConnInterface) RCenterServiceClient {
	return &rCenterServiceClient{cc}
}

func (c *rCenterServiceClient) RegisterBattleNode(ctx context.Context, in *RegisterBattleNodeRequest, opts ...grpc.CallOption) (*RegisterBattleNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterBattleNodeResponse)
	err := c.cc.Invoke(ctx, RCenterService_RegisterBattleNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCenterServiceClient) ListBattleNodes(ctx context.Context, in *ListBattleNodesRequest, opts ...grpc.CallOption) (*ListBattleNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBattleNodesResponse)
	err := c.cc.Invoke(ctx, RCenterService_ListBattleNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCenterServiceClient) StartMatch(ctx context.Context, in *StartMatchRequest, opts ...grpc.CallOption) (*StartMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartMatchResponse)
	err := c.cc.Invoke(ctx, RCenterService_StartMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCenterServiceClient) CancelMatch(ctx context.Context, in *CancelMatchRequest, opts ...grpc.CallOption) (*CancelMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelMatchResponse)
	err := c.cc.Invoke(ctx, RCenterService_CancelMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RCenterServiceServer is the server API for RCenterService service.
// All implementations must embed UnimplementedRCenterServiceServer
// for forward compatibility.
type RCenterServiceServer interface {
	RegisterBattleNode(context.Context, *RegisterBattleNodeRequest) (*RegisterBattleNodeResponse, error)
	ListBattleNodes(context.Context, *ListBattleNodesRequest) (*ListBattleNodesResponse, error)
	StartMatch(context.Context, *StartMatchRequest) (*StartMatchResponse, error)
	CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchResponse, error)
	mustEmbedUnimplementedRCenterServiceServer()
}

// UnimplementedRCenterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRCenterServiceServer struct{}

func (UnimplementedRCenterServiceServer) RegisterBattleNode(context.Context, *RegisterBattleNodeRequest) (*RegisterBattleNodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterBattleNode not implemented")
}
func (UnimplementedRCenterServiceServer) ListBattleNodes(context.Context, *ListBattleNodesRequest) (*ListBattleNodesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBattleNodes not implemented")
}
func (UnimplementedRCenterServiceServer) StartMatch(context.Context, *StartMatchRequest) (*StartMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedRCenterServiceServer) CancelMatch(context.Context, *CancelMatchRequest) (*CancelMatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelMatch not implemented")
}
func (UnimplementedRCenterServiceServer) mustEmbedUnimplementedRCenterServiceServer() {}
func (UnimplementedRCenterServiceServer) testEmbeddedByValue()                        {}

// UnsafeRCenterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RCenterServiceServer will
// result in compilation errors.
type UnsafeRCenterServiceServer interface {
	mustEmbedUnimplementedRCenterServiceServer()
}

func RegisterRCenterServiceServer(s grpc.ServiceRegistrar, srv RCenterServiceServer) {
	// If the following call panics, it indicates UnimplementedRCenterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RCenterService_ServiceDesc, srv)
}

func _RCenterService_RegisterBattleNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterBattleNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCenterServiceServer).RegisterBattleNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCenterService_RegisterBattleNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCenterServiceServer).RegisterBattleNode(ctx, req.(*RegisterBattleNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCenterService_ListBattleNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBattleNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCenterServiceServer).ListBattleNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCenterService_ListBattleNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCenterServiceServer).ListBattleNodes(ctx, req.(*ListBattleNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCenterService_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCenterServiceServer).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCenterService_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCenterServiceServer).StartMatch(ctx, req.(*StartMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCenterService_CancelMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCenterServiceServer).CancelMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCenterService_CancelMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCenterServiceServer).CancelMatch(ctx, req.(*CancelMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RCenterService_ServiceDesc is the grpc.ServiceDesc for RCenterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RCenterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rcenter.v1.RCenterService",
	HandlerType: (*RCenterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterBattleNode",
			Handler:    _RCenterService_RegisterBattleNode_Handler,
		},
		{
			MethodName: "ListBattleNodes",
			Handler:    _RCenterService_ListBattleNodes_Handler,
		},
		{
			MethodName: "StartMatch",
			Handler:    _RCenterService_StartMatch_Handler,
		},
		{
			MethodName: "CancelMatch",
			Handler:    _RCenterService_CancelMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/rcenter/v1/rcenter.proto",
}
