// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/state/v1/state.proto

package statepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash  string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	PlayerId      int64                  `protobuf:"varint,3,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_state_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Account) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *Account) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type Session struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId      int64                  `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_proto_state_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *Session) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Session) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Session) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_proto_state_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Player) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Player) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *Player) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *Player) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *CreateAccountRequest) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{4}
}

type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *GetAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

type RegisterAccountRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Username         string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PasswordHash     string                 `protobuf:"bytes,2,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	Nickname         string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar           string                 `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Email            string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Phone            string                 `protobuf:"bytes,6,opt,name=phone,proto3" json:"phone,omitempty"`
	SessionToken     string                 `protobuf:"bytes,7,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	SessionExpiresAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=session_expires_at,json=sessionExpiresAt,proto3" json:"session_expires_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterAccountRequest) Reset() {
	*x = RegisterAccountRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountRequest) ProtoMessage() {}

func (x *RegisterAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountRequest.ProtoReflect.Descriptor instead.
func (*RegisterAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *RegisterAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RegisterAccountRequest) GetPasswordHash() string {
	if x != nil {
		return x.PasswordHash
	}
	return ""
}

func (x *RegisterAccountRequest) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *RegisterAccountRequest) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *RegisterAccountRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *RegisterAccountRequest) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *RegisterAccountRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *RegisterAccountRequest) GetSessionExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SessionExpiresAt
	}
	return nil
}

type RegisterAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       *Account               `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Player        *Player                `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Session       *Session               `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterAccountResponse) Reset() {
	*x = RegisterAccountResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterAccountResponse) ProtoMessage() {}

func (x *RegisterAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterAccountResponse.ProtoReflect.Descriptor instead.
func (*RegisterAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterAccountResponse) GetAccount() *Account {
	if x != nil {
		return x.Account
	}
	return nil
}

func (x *RegisterAccountResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

func (x *RegisterAccountResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSessionRequest) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{10}
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *GetSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type GetSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Session       *Session               `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionResponse) Reset() {
	*x = GetSessionResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionResponse) ProtoMessage() {}

func (x *GetSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionResponse.ProtoReflect.Descriptor instead.
func (*GetSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *GetSessionResponse) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteSessionRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{14}
}

type CreatePlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerRequest) Reset() {
	*x = CreatePlayerRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerRequest) ProtoMessage() {}

func (x *CreatePlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerRequest.ProtoReflect.Descriptor instead.
func (*CreatePlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePlayerRequest) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type CreatePlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePlayerResponse) Reset() {
	*x = CreatePlayerResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlayerResponse) ProtoMessage() {}

func (x *CreatePlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlayerResponse.ProtoReflect.Descriptor instead.
func (*CreatePlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{16}
}

type GetPlayerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerRequest) Reset() {
	*x = GetPlayerRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerRequest) ProtoMessage() {}

func (x *GetPlayerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerRequest.ProtoReflect.Descriptor instead.
func (*GetPlayerRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{17}
}

func (x *GetPlayerRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetPlayerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Player        *Player                `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlayerResponse) Reset() {
	*x = GetPlayerResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlayerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlayerResponse) ProtoMessage() {}

func (x *GetPlayerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlayerResponse.ProtoReflect.Descriptor instead.
func (*GetPlayerResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{18}
}

func (x *GetPlayerResponse) GetPlayer() *Player {
	if x != nil {
		return x.Player
	}
	return nil
}

type NextPlayerIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPlayerIDRequest) Reset() {
	*x = NextPlayerIDRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPlayerIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPlayerIDRequest) ProtoMessage() {}

func (x *NextPlayerIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPlayerIDRequest.ProtoReflect.Descriptor instead.
func (*NextPlayerIDRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{19}
}

type NextPlayerIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NextPlayerIDResponse) Reset() {
	*x = NextPlayerIDResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NextPlayerIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NextPlayerIDResponse) ProtoMessage() {}

func (x *NextPlayerIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NextPlayerIDResponse.ProtoReflect.Descriptor instead.
func (*NextPlayerIDResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{20}
}

func (x *NextPlayerIDResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type Presence struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Presence) Reset() {
	*x = Presence{}
	mi := &file_proto_state_v1_state_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Presence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Presence) ProtoMessage() {}

func (x *Presence) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Presence.ProtoReflect.Descriptor instead.
func (*Presence) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{21}
}

func (x *Presence) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *Presence) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *Presence) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Presence) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *Presence              `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceRequest) Reset() {
	*x = SetPresenceRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceRequest) ProtoMessage() {}

func (x *SetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceRequest.ProtoReflect.Descriptor instead.
func (*SetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{22}
}

func (x *SetPresenceRequest) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

func (x *SetPresenceRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type SetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPresenceResponse) Reset() {
	*x = SetPresenceResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPresenceResponse) ProtoMessage() {}

func (x *SetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPresenceResponse.ProtoReflect.Descriptor instead.
func (*SetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{23}
}

type GetPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceRequest) Reset() {
	*x = GetPresenceRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceRequest) ProtoMessage() {}

func (x *GetPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceRequest.ProtoReflect.Descriptor instead.
func (*GetPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{24}
}

func (x *GetPresenceRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type GetPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Presence      *Presence              `protobuf:"bytes,1,opt,name=presence,proto3" json:"presence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPresenceResponse) Reset() {
	*x = GetPresenceResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPresenceResponse) ProtoMessage() {}

func (x *GetPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPresenceResponse.ProtoReflect.Descriptor instead.
func (*GetPresenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{25}
}

func (x *GetPresenceResponse) GetPresence() *Presence {
	if x != nil {
		return x.Presence
	}
	return nil
}

type ClearPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPresenceRequest) Reset() {
	*x = ClearPresenceRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPresenceRequest) ProtoMessage() {}

func (x *ClearPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPresenceRequest.ProtoReflect.Descriptor instead.
func (*ClearPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{26}
}

func (x *ClearPresenceRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *ClearPresenceRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type ClearPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearPresenceResponse) Reset() {
	*x = ClearPresenceResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearPresenceResponse) ProtoMessage() {}

func (x *ClearPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearPresenceResponse.ProtoReflect.Descriptor instead.
func (*ClearPresenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{27}
}

type RefreshPresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	ServerName    string                 `protobuf:"bytes,2,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Ttl           *durationpb.Duration   `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPresenceRequest) Reset() {
	*x = RefreshPresenceRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPresenceRequest) ProtoMessage() {}

func (x *RefreshPresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPresenceRequest.ProtoReflect.Descriptor instead.
func (*RefreshPresenceRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{28}
}

func (x *RefreshPresenceRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *RefreshPresenceRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *RefreshPresenceRequest) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RefreshPresenceRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

type RefreshPresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshPresenceResponse) Reset() {
	*x = RefreshPresenceResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshPresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshPresenceResponse) ProtoMessage() {}

func (x *RefreshPresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshPresenceResponse.ProtoReflect.Descriptor instead.
func (*RefreshPresenceResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{29}
}

type FriendRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPlayer    int64                  `protobuf:"varint,1,opt,name=from_player,json=fromPlayer,proto3" json:"from_player,omitempty"`
	ToPlayer      int64                  `protobuf:"varint,2,opt,name=to_player,json=toPlayer,proto3" json:"to_player,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FriendRequest) Reset() {
	*x = FriendRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendRequest) ProtoMessage() {}

func (x *FriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendRequest.ProtoReflect.Descriptor instead.
func (*FriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{30}
}

func (x *FriendRequest) GetFromPlayer() int64 {
	if x != nil {
		return x.FromPlayer
	}
	return 0
}

func (x *FriendRequest) GetToPlayer() int64 {
	if x != nil {
		return x.ToPlayer
	}
	return 0
}

func (x *FriendRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SendFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId  int64                  `protobuf:"varint,1,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    int64                  `protobuf:"varint,2,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestRequest) Reset() {
	*x = SendFriendRequestRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestRequest) ProtoMessage() {}

func (x *SendFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*SendFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{31}
}

func (x *SendFriendRequestRequest) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *SendFriendRequestRequest) GetToPlayerId() int64 {
	if x != nil {
		return x.ToPlayerId
	}
	return 0
}

type SendFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendFriendRequestResponse) Reset() {
	*x = SendFriendRequestResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestResponse) ProtoMessage() {}

func (x *SendFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*SendFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{32}
}

type ListFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestRequest) Reset() {
	*x = ListFriendRequestRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestRequest) ProtoMessage() {}

func (x *ListFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*ListFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{33}
}

func (x *ListFriendRequestRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ListFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Requests      []*FriendRequest       `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendRequestResponse) Reset() {
	*x = ListFriendRequestResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendRequestResponse) ProtoMessage() {}

func (x *ListFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*ListFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{34}
}

func (x *ListFriendRequestResponse) GetRequests() []*FriendRequest {
	if x != nil {
		return x.Requests
	}
	return nil
}

type HandleFriendRequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPlayerId  int64                  `protobuf:"varint,1,opt,name=from_player_id,json=fromPlayerId,proto3" json:"from_player_id,omitempty"`
	ToPlayerId    int64                  `protobuf:"varint,2,opt,name=to_player_id,json=toPlayerId,proto3" json:"to_player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestRequest) Reset() {
	*x = HandleFriendRequestRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestRequest) ProtoMessage() {}

func (x *HandleFriendRequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestRequest.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{35}
}

func (x *HandleFriendRequestRequest) GetFromPlayerId() int64 {
	if x != nil {
		return x.FromPlayerId
	}
	return 0
}

func (x *HandleFriendRequestRequest) GetToPlayerId() int64 {
	if x != nil {
		return x.ToPlayerId
	}
	return 0
}

type HandleFriendRequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandleFriendRequestResponse) Reset() {
	*x = HandleFriendRequestResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandleFriendRequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleFriendRequestResponse) ProtoMessage() {}

func (x *HandleFriendRequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleFriendRequestResponse.ProtoReflect.Descriptor instead.
func (*HandleFriendRequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{36}
}

type ListFriendIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListFriendIDsRequest) Reset() {
	*x = ListFriendIDsRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendIDsRequest) ProtoMessage() {}

func (x *ListFriendIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendIDsRequest.ProtoReflect.Descriptor instead.
func (*ListFriendIDsRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{37}
}

func (x *ListFriendIDsRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

type ListFriendIDsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	FriendPlayerIds []int64                `protobuf:"varint,1,rep,packed,name=friend_player_ids,json=friendPlayerIds,proto3" json:"friend_player_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListFriendIDsResponse) Reset() {
	*x = ListFriendIDsResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListFriendIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListFriendIDsResponse) ProtoMessage() {}

func (x *ListFriendIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListFriendIDsResponse.ProtoReflect.Descriptor instead.
func (*ListFriendIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{38}
}

func (x *ListFriendIDsResponse) GetFriendPlayerIds() []int64 {
	if x != nil {
		return x.FriendPlayerIds
	}
	return nil
}

type DeleteFriendRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlayerId       int64                  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	FriendPlayerId int64                  `protobuf:"varint,2,opt,name=friend_player_id,json=friendPlayerId,proto3" json:"friend_player_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteFriendRequest) Reset() {
	*x = DeleteFriendRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendRequest) ProtoMessage() {}

func (x *DeleteFriendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendRequest.ProtoReflect.Descriptor instead.
func (*DeleteFriendRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{39}
}

func (x *DeleteFriendRequest) GetPlayerId() int64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *DeleteFriendRequest) GetFriendPlayerId() int64 {
	if x != nil {
		return x.FriendPlayerId
	}
	return 0
}

type DeleteFriendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteFriendResponse) Reset() {
	*x = DeleteFriendResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteFriendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteFriendResponse) ProtoMessage() {}

func (x *DeleteFriendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteFriendResponse.ProtoReflect.Descriptor instead.
func (*DeleteFriendResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{40}
}

type RealtimeEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Type           string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	TargetPlayerId int64                  `protobuf:"varint,2,opt,name=target_player_id,json=targetPlayerId,proto3" json:"target_player_id,omitempty"`
	ActorPlayerId  int64                  `protobuf:"varint,3,opt,name=actor_player_id,json=actorPlayerId,proto3" json:"actor_player_id,omitempty"`
	Online         bool                   `protobuf:"varint,4,opt,name=online,proto3" json:"online,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	MatchStatus    string                 `protobuf:"bytes,6,opt,name=match_status,json=matchStatus,proto3" json:"match_status,omitempty"`
	RoomName       string                 `protobuf:"bytes,7,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	MatchToken     string                 `protobuf:"bytes,8,opt,name=match_token,json=matchToken,proto3" json:"match_token,omitempty"`
	BattleKcpAddr  string                 `protobuf:"bytes,9,opt,name=battle_kcp_addr,json=battleKcpAddr,proto3" json:"battle_kcp_addr,omitempty"`
	BattleNodeName string                 `protobuf:"bytes,10,opt,name=battle_node_name,json=battleNodeName,proto3" json:"battle_node_name,omitempty"`
	MatchPlayerIds []int64                `protobuf:"varint,11,rep,packed,name=match_player_ids,json=matchPlayerIds,proto3" json:"match_player_ids,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RealtimeEvent) Reset() {
	*x = RealtimeEvent{}
	mi := &file_proto_state_v1_state_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealtimeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealtimeEvent) ProtoMessage() {}

func (x *RealtimeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealtimeEvent.ProtoReflect.Descriptor instead.
func (*RealtimeEvent) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{41}
}

func (x *RealtimeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *RealtimeEvent) GetTargetPlayerId() int64 {
	if x != nil {
		return x.TargetPlayerId
	}
	return 0
}

func (x *RealtimeEvent) GetActorPlayerId() int64 {
	if x != nil {
		return x.ActorPlayerId
	}
	return 0
}

func (x *RealtimeEvent) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *RealtimeEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *RealtimeEvent) GetMatchStatus() string {
	if x != nil {
		return x.MatchStatus
	}
	return ""
}

func (x *RealtimeEvent) GetRoomName() string {
	if x != nil {
		return x.RoomName
	}
	return ""
}

func (x *RealtimeEvent) GetMatchToken() string {
	if x != nil {
		return x.MatchToken
	}
	return ""
}

func (x *RealtimeEvent) GetBattleKcpAddr() string {
	if x != nil {
		return x.BattleKcpAddr
	}
	return ""
}

func (x *RealtimeEvent) GetBattleNodeName() string {
	if x != nil {
		return x.BattleNodeName
	}
	return ""
}

func (x *RealtimeEvent) GetMatchPlayerIds() []int64 {
	if x != nil {
		return x.MatchPlayerIds
	}
	return nil
}

type PublishRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	Event         *RealtimeEvent         `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRealtimeRequest) Reset() {
	*x = PublishRealtimeRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRealtimeRequest) ProtoMessage() {}

func (x *PublishRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRealtimeRequest.ProtoReflect.Descriptor instead.
func (*PublishRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{42}
}

func (x *PublishRealtimeRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *PublishRealtimeRequest) GetEvent() *RealtimeEvent {
	if x != nil {
		return x.Event
	}
	return nil
}

type PublishRealtimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRealtimeResponse) Reset() {
	*x = PublishRealtimeResponse{}
	mi := &file_proto_state_v1_state_proto_msgTypes[43]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRealtimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRealtimeResponse) ProtoMessage() {}

func (x *PublishRealtimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[43]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRealtimeResponse.ProtoReflect.Descriptor instead.
func (*PublishRealtimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{43}
}

type SubscribeRealtimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRealtimeRequest) Reset() {
	*x = SubscribeRealtimeRequest{}
	mi := &file_proto_state_v1_state_proto_msgTypes[44]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRealtimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRealtimeRequest) ProtoMessage() {}

func (x *SubscribeRealtimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_state_v1_state_proto_msgTypes[44]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRealtimeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRealtimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_state_v1_state_proto_rawDescGZIP(), []int{44}
}

func (x *SubscribeRealtimeRequest) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

var File_proto_state_v1_state_proto protoreflect.FileDescriptor

const file_proto_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/state/v1/state.proto\x12\bstate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"g\n" +
	"\aAccount\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1b\n" +
	"\tplayer_id\x18\x03 \x01(\x03R\bplayerId\"w\n" +
	"\aSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\x03R\bplayerId\x129\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"x\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\"C\n" +
	"\x14CreateAccountRequest\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.state.v1.AccountR\aaccount\"\x17\n" +
	"\x15CreateAccountResponse\"/\n" +
	"\x11GetAccountRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\"A\n" +
	"\x12GetAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.state.v1.AccountR\aaccount\"\xa8\x02\n" +
	"\x16RegisterAccountRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12#\n" +
	"\rpassword_hash\x18\x02 \x01(\tR\fpasswordHash\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x04 \x01(\tR\x06avatar\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x14\n" +
	"\x05phone\x18\x06 \x01(\tR\x05phone\x12#\n" +
	"\rsession_token\x18\a \x01(\tR\fsessionToken\x12H\n" +
	"\x12session_expires_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x10sessionExpiresAt\"\x9d\x01\n" +
	"\x17RegisterAccountResponse\x12+\n" +
	"\aaccount\x18\x01 \x01(\v2\x11.state.v1.AccountR\aaccount\x12(\n" +
	"\x06player\x18\x02 \x01(\v2\x10.state.v1.PlayerR\x06player\x12+\n" +
	"\asession\x18\x03 \x01(\v2\x11.state.v1.SessionR\asession\"C\n" +
	"\x14CreateSessionRequest\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.state.v1.SessionR\asession\"\x17\n" +
	"\x15CreateSessionResponse\")\n" +
	"\x11GetSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"A\n" +
	"\x12GetSessionResponse\x12+\n" +
	"\asession\x18\x01 \x01(\v2\x11.state.v1.SessionR\asession\",\n" +
	"\x14DeleteSessionRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x17\n" +
	"\x15DeleteSessionResponse\"?\n" +
	"\x13CreatePlayerRequest\x12(\n" +
	"\x06player\x18\x01 \x01(\v2\x10.state.v1.PlayerR\x06player\"\x16\n" +
	"\x14CreatePlayerResponse\"\"\n" +
	"\x10GetPlayerRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"=\n" +
	"\x11GetPlayerResponse\x12(\n" +
	"\x06player\x18\x01 \x01(\v2\x10.state.v1.PlayerR\x06player\"\x15\n" +
	"\x13NextPlayerIDRequest\"&\n" +
	"\x14NextPlayerIDResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x9b\x01\n" +
	"\bPresence\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"q\n" +
	"\x12SetPresenceRequest\x12.\n" +
	"\bpresence\x18\x01 \x01(\v2\x12.state.v1.PresenceR\bpresence\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x15\n" +
	"\x13SetPresenceResponse\"1\n" +
	"\x12GetPresenceRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"E\n" +
	"\x13GetPresenceResponse\x12.\n" +
	"\bpresence\x18\x01 \x01(\v2\x12.state.v1.PresenceR\bpresence\"T\n" +
	"\x14ClearPresenceRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\"\x17\n" +
	"\x15ClearPresenceResponse\"\xbe\x01\n" +
	"\x16RefreshPresenceRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\"\x19\n" +
	"\x17RefreshPresenceResponse\"\x88\x01\n" +
	"\rFriendRequest\x12\x1f\n" +
	"\vfrom_player\x18\x01 \x01(\x03R\n" +
	"fromPlayer\x12\x1b\n" +
	"\tto_player\x18\x02 \x01(\x03R\btoPlayer\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"b\n" +
	"\x18SendFriendRequestRequest\x12$\n" +
	"\x0efrom_player_id\x18\x01 \x01(\x03R\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x02 \x01(\x03R\n" +
	"toPlayerId\"\x1b\n" +
	"\x19SendFriendRequestResponse\"7\n" +
	"\x18ListFriendRequestRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"P\n" +
	"\x19ListFriendRequestResponse\x123\n" +
	"\brequests\x18\x01 \x03(\v2\x17.state.v1.FriendRequestR\brequests\"d\n" +
	"\x1aHandleFriendRequestRequest\x12$\n" +
	"\x0efrom_player_id\x18\x01 \x01(\x03R\ffromPlayerId\x12 \n" +
	"\fto_player_id\x18\x02 \x01(\x03R\n" +
	"toPlayerId\"\x1d\n" +
	"\x1bHandleFriendRequestResponse\"3\n" +
	"\x14ListFriendIDsRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\"C\n" +
	"\x15ListFriendIDsResponse\x12*\n" +
	"\x11friend_player_ids\x18\x01 \x03(\x03R\x0ffriendPlayerIds\"\\\n" +
	"\x13DeleteFriendRequest\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\x03R\bplayerId\x12(\n" +
	"\x10friend_player_id\x18\x02 \x01(\x03R\x0efriendPlayerId\"\x16\n" +
	"\x14DeleteFriendResponse\"\x82\x03\n" +
	"\rRealtimeEvent\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12(\n" +
	"\x10target_player_id\x18\x02 \x01(\x03R\x0etargetPlayerId\x12&\n" +
	"\x0factor_player_id\x18\x03 \x01(\x03R\ractorPlayerId\x12\x16\n" +
	"\x06online\x18\x04 \x01(\bR\x06online\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\fmatch_status\x18\x06 \x01(\tR\vmatchStatus\x12\x1b\n" +
	"\troom_name\x18\a \x01(\tR\broomName\x12\x1f\n" +
	"\vmatch_token\x18\b \x01(\tR\n" +
	"matchToken\x12&\n" +
	"\x0fbattle_kcp_addr\x18\t \x01(\tR\rbattleKcpAddr\x12(\n" +
	"\x10battle_node_name\x18\n" +
	" \x01(\tR\x0ebattleNodeName\x12(\n" +
	"\x10match_player_ids\x18\v \x03(\x03R\x0ematchPlayerIds\"h\n" +
	"\x16PublishRealtimeRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12-\n" +
	"\x05event\x18\x02 \x01(\v2\x17.state.v1.RealtimeEventR\x05event\"\x19\n" +
	"\x17PublishRealtimeResponse\";\n" +
	"\x18SubscribeRealtimeRequest\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName2\xc7\x0e\n" +
	"\fStateService\x12P\n" +
	"\rCreateAccount\x12\x1e.state.v1.CreateAccountRequest\x1a\x1f.state.v1.CreateAccountResponse\x12G\n" +
	"\n" +
	"GetAccount\x12\x1b.state.v1.GetAccountRequest\x1a\x1c.state.v1.GetAccountResponse\x12V\n" +
	"\x0fRegisterAccount\x12 .state.v1.RegisterAccountRequest\x1a!.state.v1.RegisterAccountResponse\x12P\n" +
	"\rCreateSession\x12\x1e.state.v1.CreateSessionRequest\x1a\x1f.state.v1.CreateSessionResponse\x12G\n" +
	"\n" +
	"GetSession\x12\x1b.state.v1.GetSessionRequest\x1a\x1c.state.v1.GetSessionResponse\x12P\n" +
	"\rDeleteSession\x12\x1e.state.v1.DeleteSessionRequest\x1a\x1f.state.v1.DeleteSessionResponse\x12M\n" +
	"\fCreatePlayer\x12\x1d.state.v1.CreatePlayerRequest\x1a\x1e.state.v1.CreatePlayerResponse\x12D\n" +
	"\tGetPlayer\x12\x1a.state.v1.GetPlayerRequest\x1a\x1b.state.v1.GetPlayerResponse\x12M\n" +
	"\fNextPlayerID\x12\x1d.state.v1.NextPlayerIDRequest\x1a\x1e.state.v1.NextPlayerIDResponse\x12J\n" +
	"\vSetPresence\x12\x1c.state.v1.SetPresenceRequest\x1a\x1d.state.v1.SetPresenceResponse\x12J\n" +
	"\vGetPresence\x12\x1c.state.v1.GetPresenceRequest\x1a\x1d.state.v1.GetPresenceResponse\x12P\n" +
	"\rClearPresence\x12\x1e.state.v1.ClearPresenceRequest\x1a\x1f.state.v1.ClearPresenceResponse\x12V\n" +
	"\x0fRefreshPresence\x12 .state.v1.RefreshPresenceRequest\x1a!.state.v1.RefreshPresenceResponse\x12\\\n" +
	"\x11SendFriendRequest\x12\".state.v1.SendFriendRequestRequest\x1a#.state.v1.SendFriendRequestResponse\x12^\n" +
	"\x13ListIncomingRequest\x12\".state.v1.ListFriendRequestRequest\x1a#.state.v1.ListFriendRequestResponse\x12^\n" +
	"\x13ListOutgoingRequest\x12\".state.v1.ListFriendRequestRequest\x1a#.state.v1.ListFriendRequestResponse\x12b\n" +
	"\x13AcceptFriendRequest\x12$.state.v1.HandleFriendRequestRequest\x1a%.state.v1.HandleFriendRequestResponse\x12b\n" +
	"\x13RejectFriendRequest\x12$.state.v1.HandleFriendRequestRequest\x1a%.state.v1.HandleFriendRequestResponse\x12P\n" +
	"\rListFriendIDs\x12\x1e.state.v1.ListFriendIDsRequest\x1a\x1f.state.v1.ListFriendIDsResponse\x12M\n" +
	"\fDeleteFriend\x12\x1d.state.v1.DeleteFriendRequest\x1a\x1e.state.v1.DeleteFriendResponse\x12V\n" +
	"\x0fPublishRealtime\x12 .state.v1.PublishRealtimeRequest\x1a!.state.v1.PublishRealtimeResponse\x12R\n" +
	"\x11SubscribeRealtime\x12\".state.v1.SubscribeRealtimeRequest\x1a\x17.state.v1.RealtimeEvent0\x01B*Z(server/internal/contract/statepb;statepbb\x06proto3"

var (
	file_proto_state_v1_state_proto_rawDescOnce sync.Once
	file_proto_state_v1_state_proto_rawDescData []byte
)

func file_proto_state_v1_state_proto_rawDescGZIP() []byte {
	file_proto_state_v1_state_proto_rawDescOnce.Do(func() {
		file_proto_state_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_state_v1_state_proto_rawDesc), len(file_proto_state_v1_state_proto_rawDesc)))
	})
	return file_proto_state_v1_state_proto_rawDescData
}

var file_proto_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 45)
var file_proto_state_v1_state_proto_goTypes = []any{
	(*Account)(nil),                     // 0: state.v1.Account
	(*Session)(nil),                     // 1: state.v1.Session
	(*Player)(nil),                      // 2: state.v1.Player
	(*CreateAccountRequest)(nil),        // 3: state.v1.CreateAccountRequest
	(*CreateAccountResponse)(nil),       // 4: state.v1.CreateAccountResponse
	(*GetAccountRequest)(nil),           // 5: state.v1.GetAccountRequest
	(*GetAccountResponse)(nil),          // 6: state.v1.GetAccountResponse
	(*RegisterAccountRequest)(nil),      // 7: state.v1.RegisterAccountRequest
	(*RegisterAccountResponse)(nil),     // 8: state.v1.RegisterAccountResponse
	(*CreateSessionRequest)(nil),        // 9: state.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),       // 10: state.v1.CreateSessionResponse
	(*GetSessionRequest)(nil),           // 11: state.v1.GetSessionRequest
	(*GetSessionResponse)(nil),          // 12: state.v1.GetSessionResponse
	(*DeleteSessionRequest)(nil),        // 13: state.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),       // 14: state.v1.DeleteSessionResponse
	(*CreatePlayerRequest)(nil),         // 15: state.v1.CreatePlayerRequest
	(*CreatePlayerResponse)(nil),        // 16: state.v1.CreatePlayerResponse
	(*GetPlayerRequest)(nil),            // 17: state.v1.GetPlayerRequest
	(*GetPlayerResponse)(nil),           // 18: state.v1.GetPlayerResponse
	(*NextPlayerIDRequest)(nil),         // 19: state.v1.NextPlayerIDRequest
	(*NextPlayerIDResponse)(nil),        // 20: state.v1.NextPlayerIDResponse
	(*Presence)(nil),                    // 21: state.v1.Presence
	(*SetPresenceRequest)(nil),          // 22: state.v1.SetPresenceRequest
	(*SetPresenceResponse)(nil),         // 23: state.v1.SetPresenceResponse
	(*GetPresenceRequest)(nil),          // 24: state.v1.GetPresenceRequest
	(*GetPresenceResponse)(nil),         // 25: state.v1.GetPresenceResponse
	(*ClearPresenceRequest)(nil),        // 26: state.v1.ClearPresenceRequest
	(*ClearPresenceResponse)(nil),       // 27: state.v1.ClearPresenceResponse
	(*RefreshPresenceRequest)(nil),      // 28: state.v1.RefreshPresenceRequest
	(*RefreshPresenceResponse)(nil),     // 29: state.v1.RefreshPresenceResponse
	(*FriendRequest)(nil),               // 30: state.v1.FriendRequest
	(*SendFriendRequestRequest)(nil),    // 31: state.v1.SendFriendRequestRequest
	(*SendFriendRequestResponse)(nil),   // 32: state.v1.SendFriendRequestResponse
	(*ListFriendRequestRequest)(nil),    // 33: state.v1.ListFriendRequestRequest
	(*ListFriendRequestResponse)(nil),   // 34: state.v1.ListFriendRequestResponse
	(*HandleFriendRequestRequest)(nil),  // 35: state.v1.HandleFriendRequestRequest
	(*HandleFriendRequestResponse)(nil), // 36: state.v1.HandleFriendRequestResponse
	(*ListFriendIDsRequest)(nil),        // 37: state.v1.ListFriendIDsRequest
	(*ListFriendIDsResponse)(nil),       // 38: state.v1.ListFriendIDsResponse
	(*DeleteFriendRequest)(nil),         // 39: state.v1.DeleteFriendRequest
	(*DeleteFriendResponse)(nil),        // 40: state.v1.DeleteFriendResponse
	(*RealtimeEvent)(nil),               // 41: state.v1.RealtimeEvent
	(*PublishRealtimeRequest)(nil),      // 42: state.v1.PublishRealtimeRequest
	(*PublishRealtimeResponse)(nil),     // 43: state.v1.PublishRealtimeResponse
	(*SubscribeRealtimeRequest)(nil),    // 44: state.v1.SubscribeRealtimeRequest
	(*timestamppb.Timestamp)(nil),       // 45: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),         // 46: google.protobuf.Duration
}
var file_proto_state_v1_state_proto_depIdxs = []int32{
	45, // 0: state.v1.Session.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 1: state.v1.CreateAccountRequest.account:type_name -> state.v1.Account
	0,  // 2: state.v1.GetAccountResponse.account:type_name -> state.v1.Account
	45, // 3: state.v1.RegisterAccountRequest.session_expires_at:type_name -> google.protobuf.Timestamp
	0,  // 4: state.v1.RegisterAccountResponse.account:type_name -> state.v1.Account
	2,  // 5: state.v1.RegisterAccountResponse.player:type_name -> state.v1.Player
	1,  // 6: state.v1.RegisterAccountResponse.session:type_name -> state.v1.Session
	1,  // 7: state.v1.CreateSessionRequest.session:type_name -> state.v1.Session
	1,  // 8: state.v1.GetSessionResponse.session:type_name -> state.v1.Session
	2,  // 9: state.v1.CreatePlayerRequest.player:type_name -> state.v1.Player
	2,  // 10: state.v1.GetPlayerResponse.player:type_name -> state.v1.Player
	45, // 11: state.v1.Presence.updated_at:type_name -> google.protobuf.Timestamp
	21, // 12: state.v1.SetPresenceRequest.presence:type_name -> state.v1.Presence
	46, // 13: state.v1.SetPresenceRequest.ttl:type_name -> google.protobuf.Duration
	21, // 14: state.v1.GetPresenceResponse.presence:type_name -> state.v1.Presence
	45, // 15: state.v1.RefreshPresenceRequest.updated_at:type_name -> google.protobuf.Timestamp
	46, // 16: state.v1.RefreshPresenceRequest.ttl:type_name -> google.protobuf.Duration
	45, // 17: state.v1.FriendRequest.created_at:type_name -> google.protobuf.Timestamp
	30, // 18: state.v1.ListFriendRequestResponse.requests:type_name -> state.v1.FriendRequest
	41, // 19: state.v1.PublishRealtimeRequest.event:type_name -> state.v1.RealtimeEvent
	3,  // 20: state.v1.StateService.CreateAccount:input_type -> state.v1.CreateAccountRequest
	5,  // 21: state.v1.StateService.GetAccount:input_type -> state.v1.GetAccountRequest
	7,  // 22: state.v1.StateService.RegisterAccount:input_type -> state.v1.RegisterAccountRequest
	9,  // 23: state.v1.StateService.CreateSession:input_type -> state.v1.CreateSessionRequest
	11, // 24: state.v1.StateService.GetSession:input_type -> state.v1.GetSessionRequest
	13, // 25: state.v1.StateService.DeleteSession:input_type -> state.v1.DeleteSessionRequest
	15, // 26: state.v1.StateService.CreatePlayer:input_type -> state.v1.CreatePlayerRequest
	17, // 27: state.v1.StateService.GetPlayer:input_type -> state.v1.GetPlayerRequest
	19, // 28: state.v1.StateService.NextPlayerID:input_type -> state.v1.NextPlayerIDRequest
	22, // 29: state.v1.StateService.SetPresence:input_type -> state.v1.SetPresenceRequest
	24, // 30: state.v1.StateService.GetPresence:input_type -> state.v1.GetPresenceRequest
	26, // 31: state.v1.StateService.ClearPresence:input_type -> state.v1.ClearPresenceRequest
	28, // 32: state.v1.StateService.RefreshPresence:input_type -> state.v1.RefreshPresenceRequest
	31, // 33: state.v1.StateService.SendFriendRequest:input_type -> state.v1.SendFriendRequestRequest
	33, // 34: state.v1.StateService.ListIncomingRequest:input_type -> state.v1.ListFriendRequestRequest
	33, // 35: state.v1.StateService.ListOutgoingRequest:input_type -> state.v1.ListFriendRequestRequest
	35, // 36: state.v1.StateService.AcceptFriendRequest:input_type -> state.v1.HandleFriendRequestRequest
	35, // 37: state.v1.StateService.RejectFriendRequest:input_type -> state.v1.HandleFriendRequestRequest
	37, // 38: state.v1.StateService.ListFriendIDs:input_type -> state.v1.ListFriendIDsRequest
	39, // 39: state.v1.StateService.DeleteFriend:input_type -> state.v1.DeleteFriendRequest
	42, // 40: state.v1.StateService.PublishRealtime:input_type -> state.v1.PublishRealtimeRequest
	44, // 41: state.v1.StateService.SubscribeRealtime:input_type -> state.v1.SubscribeRealtimeRequest
	4,  // 42: state.v1.StateService.CreateAccount:output_type -> state.v1.CreateAccountResponse
	6,  // 43: state.v1.StateService.GetAccount:output_type -> state.v1.GetAccountResponse
	8,  // 44: state.v1.StateService.RegisterAccount:output_type -> state.v1.RegisterAccountResponse
	10, // 45: state.v1.StateService.CreateSession:output_type -> state.v1.CreateSessionResponse
	12, // 46: state.v1.StateService.GetSession:output_type -> state.v1.GetSessionResponse
	14, // 47: state.v1.StateService.DeleteSession:output_type -> state.v1.DeleteSessionResponse
	16, // 48: state.v1.StateService.CreatePlayer:output_type -> state.v1.CreatePlayerResponse
	18, // 49: state.v1.StateService.GetPlayer:output_type -> state.v1.GetPlayerResponse
	20, // 50: state.v1.StateService.NextPlayerID:output_type -> state.v1.NextPlayerIDResponse
	23, // 51: state.v1.StateService.SetPresence:output_type -> state.v1.SetPresenceResponse
	25, // 52: state.v1.StateService.GetPresence:output_type -> state.v1.GetPresenceResponse
	27, // 53: state.v1.StateService.ClearPresence:output_type -> state.v1.ClearPresenceResponse
	29, // 54: state.v1.StateService.RefreshPresence:output_type -> state.v1.RefreshPresenceResponse
	32, // 55: state.v1.StateService.SendFriendRequest:output_type -> state.v1.SendFriendRequestResponse
	34, // 56: state.v1.StateService.ListIncomingRequest:output_type -> state.v1.ListFriendRequestResponse
	34, // 57: state.v1.StateService.ListOutgoingRequest:output_type -> state.v1.ListFriendRequestResponse
	36, // 58: state.v1.StateService.AcceptFriendRequest:output_type -> state.v1.HandleFriendRequestResponse
	36, // 59: state.v1.StateService.RejectFriendRequest:output_type -> state.v1.HandleFriendRequestResponse
	38, // 60: state.v1.StateService.ListFriendIDs:output_type -> state.v1.ListFriendIDsResponse
	40, // 61: state.v1.StateService.DeleteFriend:output_type -> state.v1.DeleteFriendResponse
	43, // 62: state.v1.StateService.PublishRealtime:output_type -> state.v1.PublishRealtimeResponse
	41, // 63: state.v1.StateService.SubscribeRealtime:output_type -> state.v1.RealtimeEvent
	42, // [42:64] is the sub-list for method output_type
	20, // [20:42] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_proto_state_v1_state_proto_init() }
func file_proto_state_v1_state_proto_init() {
	if File_proto_state_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_state_v1_state_proto_rawDesc), len(file_proto_state_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   45,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_state_v1_state_proto_goTypes,
		DependencyIndexes: file_proto_state_v1_state_proto_depIdxs,
		MessageInfos:      file_proto_state_v1_state_proto_msgTypes,
	}.Build()
	File_proto_state_v1_state_proto = out.File
	file_proto_state_v1_state_proto_goTypes = nil
	file_proto_state_v1_state_proto_depIdxs = nil
}
